### ISSUE TITLE
规范文档排版：中文与英文/数字之间是否添加空格存在多处混用

### ISSUE THREAD

**Issue by greyli** [vesoft-inc/nebula-docs-cn#1047]
目前文档中整体是不添加空格的，但是有很多地方还是添加了空格，比如文档第一页的[这一节](https://docs.nebula-graph.com.cn/2.5.0/1.introduction/1.what-is-nebula-graph/#opencypher)以及下一节部分添加了空格，后面的多个页面中提示/注意段落都添加了空格。

建议在中文与英文/数字之间添加空格以增加可读性（参考[中文文案排版指北](https://github.com/sparanoid/chinese-copywriting-guidelines)），或是去掉空格以保持全文档一致。同时在贡献指南中明确排版约定。

另外文档中还存在中英文标点混用的情况。

**Comment by abby-cyber** [comment]
thank you for your suggestions, we've fixed the whitespace issue.
