### ISSUE TITLE
Nebula Spark Connector读取出来的默认vertexId和edge srcId dstId的列名叫什么

### ISSUE THREAD

**Issue by stormrise** [vesoft-inc/nebula-docs-cn#1090]
Nebula Spark Connector 缺乏一些默认读取出来后的列名叫啥

**Comment by Nicole00** [comment]
> Nebula Spark Connector 缺乏一些默认读取出来后的列名叫啥

默认vertexId 列名叫 _vertexId
默认edge srcid 列名叫 _srcId
默认edge dstid 列名叫 _dstId
默认edge rank 列名叫 _rank

**Comment by wey-gu** [comment]
@Nicole00 shall we document information in docs?
