### ISSUE TITLE
`move_file` explanation for exchange sst

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1183]
https://docs.nebula-graph.com.cn/2.6.1/nebula-exchange/use-exchange/ex-ug-import-from-sst/

Quote what @darionyaphet helped correct on this:

> 更正一下 move_file 不是删除download 目录 而是将SST文件移动到data 目录下 默认操作是 copy （非move）的

context: https://discuss.nebula-graph.com.cn/t/topic/6337/7

**Comment by wey-gu** [comment]
- [ ] to lift en docs

**Comment by darionyaphet** [comment]
`Can be set to true to move the files instead of copying them.`   Quoted from IngestExternalFileOptions in `options.h`

**Comment by randomJoe211** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/1188/
Thanks for the heads-up. The CN docs have been modified and the EN docs will be updated soon.
