### ISSUE TITLE
nGQL指南-图空间语句-USE SPACE缺少schema的设定

### ISSUE THREAD

**Issue by even1111112** [vesoft-inc/nebula-docs-cn#1215]
https://docs.nebula-graph.com.cn/2.6.1/3.ngql-guide/9.space-statements/2.use-space/
未创建space1、space2就使用

**Comment by cooper-lzy** [comment]
added the following:

# The following example creates two sample spaces.
nebula> CREATE SPACE IF NOT EXISTS space1 (vid_type=FIXED_STRING(30));
nebula> CREATE SPACE IF NOT EXISTS space2 (vid_type=FIXED_STRING(30));
