### ISSUE TITLE
全文索引

### ISSUE THREAD

**Issue by zhaochuanyun** [vesoft-inc/nebula-docs-cn#1237]
https://docs.nebula-graph.com.cn/2.6.1/4.deployment-and-installation/6.deploy-text-based-index/2.deploy-es/

登录文本搜索客户端
SIGN IN TEXT SERVICE [(<elastic_ip:port> [,<username>, <password>]), (<elastic_ip:port>), ...];

这一块应该是
SIGN IN TEXT SERVICE [(<elastic_ip:port> [<username>, <password>]), (<elastic_ip:port>), ...];且username和password均应该有引号

**Comment by wey-gu** [comment]
Thanks @zhaochuanyun!

Would you mind helping fix it with a PR? It could be done inside the GitHub Web Site by clicking the ✏️ icon on the corresponding Doc page, which will link you to the write file to edit in GitHub Web.

Thanks.

**Comment by randomJoe211** [comment]
Fixed.
