### ISSUE TITLE
nebula-importer guide missing binary package option

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1261]
There had been someone asking me on building nebula-importer step by step w/o knowing that we have binary deliverables for it.

Today someone else queried me again on this and I just realize that in documentation we only mentioned the go build or docker method on using importer.

Actually, we all know that the binary package is much easier to do so, given that the user may not familiar with the docker(what does `-v` mean to know how the config file and data should be placed inside the docker).

Thus I think we should highlight that it's easier to download the binary package before trying to build it.

https://docs.nebula-graph.com.cn/2.6.1/nebula-importer/use-importer/

**Comment by cooper-lzy** [comment]
Good idea, we have been added the method for downloading binary package directly.
