### ISSUE TITLE
conf change procedure for both docker and k8s operator deployment

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1275]
This would be nice to be added with examples/or as pointers to the existing chapter if we have the bandwidth to add so.

To be added here: https://docs.nebula-graph.io/2.6.1/5.configurations-and-logs/1.configurations/1.configurations/#modify_configurations may help.

**Comment by randomJoe211** [comment]
@abby-cyber Please evaluate this requirement.

**Comment by wey-gu** [comment]
Some context/ info may help https://siwei.io/sketches/nebula-config-explained/

**Comment by abby-cyber** [comment]
done, see [PR](https://github.com/vesoft-inc/nebula-docs-cn/pull/1297/files) & [Doc](https://docs.nebula-graph.com.cn/2.6.1/5.configurations-and-logs/1.configurations/1.configurations/)

btw: English documents are also synchronized.
