### ISSUE TITLE
Conf: `query_concurrently` in docs

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1281]
Shouldn't we document this option either on the conf guide or tuning guide, please?

https://github.com/vesoft-inc/nebula-storage/pull/503

Thanks.

- [ ] lift to en docs

**Comment by randomJoe211** [comment]
The docs only document flags in the configuration templates. The flag `--query_concurrently` is not in them. 
And looks like this feature has not been released? @Sophie-Xie Please take a look.
I'm closing this issue for now.
