### ISSUE TITLE
highlight properties limited to be used in yield(rather than in WHERE for now)

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1306]
This should be highlighted before the next release.

- [ ] en doc lift

**Comment by wey-gu** [comment]
- https://discuss.nebula-graph.com.cn/t/topic/6803/4
- https://discuss.nebula-graph.com.cn/t/topic/6696/2

**Comment by wey-gu** [comment]
Just noticed that we have examples of using properties in GO/LOOKUP queries, we should consider reverting them in the 2.6.1 branch.

**Comment by cooper-lzy** [comment]
These problems are in the document, but the WHERE clause in the GO statement can use properties. Maybe this is a bug?

![image](https://user-images.githubusercontent.com/78672629/144960751-74301f67-962b-4933-974c-bc8ace6496fb.png)
![image](https://user-images.githubusercontent.com/78672629/144960773-c512c6a5-c0b5-4ae0-8c32-a1aa7e562d20.png)

**Comment by wey-gu** [comment]
@nevermore3 could you please kindly help clarify that `the limitation in 2.6.1 that properties() cannot be used in where clause` applies on `MATCH` only, that is, it's already supported on GO/LOOKUP expressions?

**Comment by cooper-lzy** [comment]
Consult the developer to confirm that the above problem is an unexpected situation, and we will change the documentation.

**Comment by wey-gu** [comment]
> Consult the developer to confirm that the above problem is an unexpected situation, and we will change the documentation.

Got it, thanks @cooper-lzy!

**Comment by cooper-lzy** [comment]
![image](https://user-images.githubusercontent.com/78672629/144962466-c5bc695c-700b-4123-9052-d60a14e7082c.png)
