### ISSUE TITLE
写入nebula报错

### ISSUE THREAD

**Issue by Amazing1226** [vesoft-inc/nebula-docs-cn#1320]
manticError: The maximum number of statements allowed has been exceeded | com.vesoft.nebula.connector.writer.NebulaVertexWriter.submit(NebulaWriter.scala:52)

**Comment by randomJoe211** [comment]
Seems like an error message of Nebula Spark Connector? If you run into problems while using Nebula Spark Connector, please submit an issue in its repository or ask for help in the forums.
https://github.com/vesoft-inc/nebula-spark-connector
https://discuss.nebula-graph.io/
https://discuss.nebula-graph.com.cn/
