### ISSUE TITLE
add some usable datasets(from different sources) in the learning path or other page

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1388]
- basketballplayer
- ldbc (https://github.com/vesoft-inc/nebula-bench)
- livejournal (https://siwei.io/nebula-livejournal/#nebula-livejournal)
- Chinese(knowledge graph https://www.kaggle.com/littlewey/nebula-ownthink-property-graph ) https://github.com/jievince/rdf-converter
- corp relation shareholding: https://www.kaggle.com/littlewey/nebula-graph-shareolding-dataset https://github.com/wey-gu/nebula-shareholding-example
- dataset from https://nebula-graph.com.cn/demo/
- others(add link for others to contribute)

This is helpful for users to play with nebula easier and also enable collaboration in the community.

Is this good to go?

**Comment by whitewum** [comment]
basketballplayer is the default dataset for the doc.

LDBC is used for nebula-bench (for tests, and learn as well).

It is not necessary to add too many data sets to make users confused.

**Comment by wey-gu** [comment]
ping @QingZ11

**Comment by wey-gu** [comment]
more to go
- movie: https://www.siwei.io/nebulagraph-etl-dbt/ , https://github.com/wey-gu/movie-recommendation-dataset
- freebase: https://github.com/wey-gu/freebase-subset wip
- https://github.com/wey-gu/supplychain-dataset-gen, wip
- OpenStack https://github.com/wey-gu/openstack-graph
- K8s https://github.com/wey-gu/k8s-graph
- https://github.com/wey-gu/nebulagraph-yelp-frauddetection for gnn
- https://github.com/wey-gu/covid-track-graph-datagen
- https://github.com/wey-gu/fraud-detection-datagen (highly recommended )
- (see studio starter dataset) ...

**Comment by wey-gu** [comment]
- https://github.com/wey-gu/identity-correlation-datagen , wip
