### ISSUE TITLE
Exchange文档的application.conf链接404

### ISSUE THREAD

**Issue by ianhhhhhhhhe** [vesoft-inc/nebula-docs-cn#1413]
https://docs.nebula-graph.io/2.6.1/nebula-exchange/ex-ug-compile

这个页面的 [application.conf](https://github.com/vesoft-inc/nebula-exchange/blob/master/nebula-exchange/src/main/resources/application.conf) 应该是旧的地址，看repo，src已经移到对应标有spark版本的目录里：

https://github.com/vesoft-inc/nebula-exchange/blob/master/nebula-exchange_spark_2.4/src/main/resources/application.conf

**Comment by randomJoe211** [comment]
Thank you for the heads up. I got the 2.6.1 branch fixed and other branches will be fixed soon.
