### ISSUE TITLE
k8s nebula-graphd pod启动不了

### ISSUE THREAD

**Issue by dockerxu123** [vesoft-inc/nebula-docs-cn#1420]
k8s nebula-operator方式部署其中nebula-graphd启动不了  日志也没有报错  pod不断重启 其它组件的pod没有问题  版本是2.6.1 求助

**Comment by wey-gu** [comment]
只有 graphD 启动不了对么？有可能是这个原因，您的 node 是什么操作系统，是不是 cgroupv2 的？

https://github.com/vesoft-inc/nebula/issues/3278

**Comment by wey-gu** [comment]
this topic was continued in nebula-operator, closing it.
