### ISSUE TITLE
Eco tool image update

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1432]
https://docs.nebula-graph.com.cn/3.0.0/20.appendix/6.eco-tool-version/

Could we have an updated version of this page ;-)? (like NORM, nebula-node, .net and PHP to be included?)

Thanks!

**Comment by whitewum** [comment]
Are they released by PM?

**Comment by wey-gu** [comment]
> Are they released by PM?

No, ok now I understand that they should be firstly released :-P

**Comment by abby-cyber** [comment]
added a note for these tools in the "clients" doc #1622

**Comment by wey-gu** [comment]
with #1622 , maybe we could draw them in different color/zone ? :-D 
cc @whitewum
