### ISSUE TITLE
`add hosts` to be highlighted in deployment chapters

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1492]
This behavior change would confuse fresh or even experienced upgrade users.

- [x] Docker Compose deployment via https://github.com/vesoft-inc/nebula-docs-cn/pull/1514
- [ ] Binary Package
- [ ] Complie
- [ ] K8s is not yet relevant now as operator is not supporting 3.0 yet
- [ ] service start

**Comment by SuperYoko** [comment]
GJ!

**Comment by abby-cyber** [comment]
A note has been added in the "manage services" doc #1618  #1619 #1620 
Thanks for your feedback and suggestions.
