### ISSUE TITLE
br备份 文档和b站视频里面说的不一样

### ISSUE THREAD

**Issue by GoGoMonkey123** [vesoft-inc/nebula-docs-cn#1639]
仅支持单 metad 部署的本地文件的自动部署和恢复 -----应该是-----> 仅支持单 metad 部署的本地文件的自动备份和恢复

**Comment by foesa-yang** [comment]
Thank you for your concern, I have fix it in this pr.
https://github.com/vesoft-inc/nebula-docs-cn/pull/1685
