### ISSUE TITLE
nebula-cpp gcc version not match

### ISSUE THREAD

**Issue by mizy** [vesoft-inc/nebula-docs-cn#1697]
GCC version can't be 11 ,cause the source code can't match the preset version
![image](https://user-images.githubusercontent.com/7129229/164591441-78c176d6-b40e-4c27-9c6b-346f7be19d53.png)

**Comment by Shylock-Hg** [comment]
gcc supporting of nebula-cpp is different from nebula

**Comment by dutor** [comment]
> gcc supporting of nebula-cpp is different from nebula

Yes. Those versions in the snapshot are for Nebula build itself.

**Comment by abby-cyber** [comment]
I‘m still a little confused, so what are the current versions for nebula cpp?

**Comment by Shylock-Hg** [comment]
> I‘m still a little confused, so what are the current versions for nebula cpp?

The release is built by gcc9.3, if it's incompatible with your environment you could build it in your environment.

**Comment by dutor** [comment]
> 

e.g. GCC 4.8 is for the user of nebula-cpp to build their own applications, while GCC 10.1.0 is for us to build nebula-cpp and nebula core themselves.

**Comment by abby-cyber** [comment]
Thank you, guys! The related descriptions have been updated in the doc https://docs.nebula-graph.com.cn/3.1.0/14.client/3.nebula-cpp-client/
