### ISSUE TITLE
highlight known issue on exchange sst

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1776]
- https://github.com/vesoft-inc/nebula-exchange/issues/71
- https://discuss.nebula-graph.com.cn/t/topic/8438/18?u=wey

It seems `repartitionWithNebula: False` is with issues, we should highlight the known issue/guide user to turn it on faster before we fixed/changed default value.

quoted from second URL in above
> 
> 4.需要在-c 的exchange.conf配置文件里，强制指定： repartitionWithNebula: true，文档位置：[配置参数 - Nebula Graph Database 手册](https://docs.nebula-graph.com.cn/3.0.1/nebula-exchange/parameter-reference/ex-ug-parameter/#sst)
这里有bug，具体信息参考：[exchange 3.0 的生成的sst只包含不带tagID的数据 1](https://discuss.nebula-graph.com.cn/t/topic/7800)
https://github.com/vesoft-inc/nebula-exchange/issues/71
[https://github.com/vesoft-inc/nebula-exchange/pull/49 1](https://github.com/vesoft-inc/nebula-exchange/pull/49)

**Comment by cooper-lzy** [comment]
We do not provide the function of generating local SST files. Currently, we only support uploading to HDFS after generation. It is not clear whether the problem is caused by this process, we need @Nicole00 to help confirm.

**Comment by cooper-lzy** [comment]
The parameter `repartitionWithNebula ` defaults to true and the documentation has been updated
