### ISSUE TITLE
Why do I still need to know the id of the vertixes while I use "where" to find the vertixes

### ISSUE THREAD

**Issue by Timaos123** [vesoft-inc/nebula-docs-cn#180]
The code is just like this:
`UPSERT VERTEX 111 SET player.name = "Dwight Howard", player.age = $^.player.age + 11 WHEN $^.player.name == "Ben Simmons" && $^.player.age > 20 YIELD $^.player.name AS Name, $^.player.age AS Age;`

**Comment by whitewum** [comment]
please  raise issue in https://github.com/vesoft-inc/nebula-graph

**Comment by whitewum** [comment]
and remember to build index
