### ISSUE TITLE
search is broken in doc-cn 3.1.0

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1826]
https://docs.nebula-graph.com.cn/3.1.0/

<img width="1796" alt="Screen Shot 2022-05-24 at 5 00 14 PM" src="https://user-images.githubusercontent.com/1651790/169993388-7cacfcef-13a7-4013-832e-c2f8bf5fb4a4.png">

**Comment by randomJoe211** [comment]
On it, aaaaaaaaaaaaand...
Fixed.
