### ISSUE TITLE
request docs: delete a Nebula Cloud solutuion

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1850]
maybe we should cover this topic in docs as well?

**Comment by wey-gu** [comment]
stop solution is all we need, right?

https://docs.nebula-graph.com.cn/2.6.2/nebula-cloud/5.solution/5.0.introduce-solution/

**Comment by abby-cyber** [comment]
The cloud-related docs are removed starting from 3.5.0
