### ISSUE TITLE
es version info on fulltext index

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#1927]
maybe we could mark only es7 was tested working?

ref: https://discuss.nebula-graph.com.cn/t/topic/9280?u=wey

**Comment by abby-cyber** [comment]
> maybe we could mark only es7 was tested working?
> 
> ref: https://discuss.nebula-graph.com.cn/t/topic/9280?u=wey

Fixed. Thank you for pointing it out!
