### ISSUE TITLE
suggest to add single tab to show the example dataset like baskteball

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula-docs-cn#1928]
Detail suggestions:

1.  Add a single menu tab to show the example dataset, which help new users quickly find the example data.
2. Beside the basketball-player dataset, we can enrich other common dataset such as social network, bank transfer

**Comment by wey-gu** [comment]
some input

- https://github.com/vesoft-inc/nebula-docs-cn/issues/1388 (listed months ago, with livejournal, etc.)
- https://github.com/wey-gu/covid-track-graph-datagen (covid dummy graph)
- https://github.com/wey-gu/fraud-detection-datagen (fraud detection)

**Comment by whitewum** [comment]
1. Sure
2. basketball-player is almost the same as the UT cases in nebula Core
