### ISSUE TITLE
返回属性时必须额外指定 Tag 名称的问题

### ISSUE THREAD

**Issue by homealim2012** [vesoft-inc/nebula-docs-cn#1964]
从 3.0.0 版本开始，为了区别不同 Tag 的属性，返回属性时必须额外指定 Tag 名称。即从RETURN <变量名>.<属性名>改为RETURN <变量名>.<Tag名>.<属性名>。

但是有些业务场景需要直接匹配  <变量名>.<属性名> ，请问Tag名能否支持通配符？

**Comment by homealim2012** [comment]
比如根据(v1) - [] - (v2)匹配出来的v2的Tag很有可能时不确定的

**Comment by wey-gu** [comment]
Now, you could return `properties(v).name` when you have to :)

**Comment by homealim2012** [comment]
但是 
match (v) where properties(v).name == 'n1' return v
match (v) -[] - (v2) where properties(v2).name == 'n2' return v
返回：[ERROR (-1005)]: Scan vertices or edges need to specify a limit number, or limit number can not push down.
match (v:t1) where properties(v).name == 'n1' return v
或者  match (v) -[] - (v2:t2) where properties(v2).name == 'n2' return v
能够正常返回结果

**Comment by abby-cyber** [comment]
> 从 3.0.0 版本开始，为了区别不同 Tag 的属性，返回属性时必须额外指定 Tag 名称。即从RETURN <变量名>.<属性名>改为RETURN <变量名>.<Tag名>.<属性名>。
> 
> 但是有些业务场景需要直接匹配 <变量名>.<属性名> ，请问Tag名能否支持通配符？

目前暂时不支持喔。

**Comment by abby-cyber** [comment]
> 但是 match (v) where properties(v).name == 'n1' return v match (v) -[] - (v2) where properties(v2).name == 'n2' return v 返回：[ERROR (-1005)]: Scan vertices or edges need to specify a limit number, or limit number can not push down. match (v:t1) where properties(v).name == 'n1' return v 或者 match (v) -[] - (v2:t2) where properties(v2).name == 'n2' return v 能够正常返回结果

properties()无法解析索引，需要在match中指定索引。
