### ISSUE TITLE
Add procedure for scale-out, scale-in, server replacement chapters

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2001]
The procedure should be provided in a searchable manner :)

For scale-in, the key step is to `balance data remove`.

https://docs.nebula-graph.io/3.1.0/synchronization-and-migration/2.balance-syntax/

note: we already have scaling chapters for the nebulagraph k8s operator.

**Comment by wey-gu** [comment]
ref on scale-in: https://discuss.nebula-graph.com.cn/t/topic/9213/2

**Comment by abby-cyber** [comment]
> ref on scale-in: https://discuss.nebula-graph.com.cn/t/topic/9213/2

https://docs.nebula-graph.io/3.1.0/20.appendix/0.FAQ/#how_to_scale_out_or_scale_in_enterprise_edition_only

**Comment by wey-gu** [comment]
@abby-cyber got it, this information is the one! But it's actually not that easy for user(to seek for how to scale-in/out by searching in docs), thus I think adding a chapter may still worth it?

<img width="1295" alt="Screen Shot 2022-07-22 at 11 52 17 AM" src="https://user-images.githubusercontent.com/1651790/180358878-ac24c88b-1206-4ed1-85d0-777cf86a61c0.png">

**Comment by abby-cyber** [comment]
Yeah, will consider it after the auto scaling commands are developed. Currently, uses can refer to FAQ for manual scaling operations.

**Comment by abby-cyber** [comment]
> Yeah, will consider it after the auto scaling commands are developed. Currently, uses can refer to FAQ for manual scaling operations.

Yeah, will consider it after the auto scaling commands are developed. Currently, uses can refer to FAQ for manual scaling operations.
