### ISSUE TITLE
logo is broken

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2033]
https://cloud-cdn.nebula-graph.com.cn/vesoft-nebula-logo-white.png

<img width="454" alt="Screen Shot 2022-07-29 at 10 31 56 AM" src="https://user-images.githubusercontent.com/1651790/181670612-2e61deb6-cdd4-4392-a47b-65b1e22d490a.png">

**Comment by abby-cyber** [comment]
> https://cloud-cdn.nebula-graph.com.cn/vesoft-nebula-logo-white.png
> 
> <img alt="Screen Shot 2022-07-29 at 10 31 56 AM" width="454" src="https://user-images.githubusercontent.com/1651790/181670612-2e61deb6-cdd4-4392-a47b-65b1e22d490a.png">

It's been restored.
