### ISSUE TITLE
[ERROR (-1005)]: Host not enough!

### ISSUE THREAD

**Issue by yaya159456** [vesoft-inc/nebula-docs-cn#2069]
![image](https://user-images.githubusercontent.com/44463912/184467334-6d1b5480-c25a-48e1-8a25-5962c10b8d47.png)
单节点部署了一个nebula，添加图空间的时候报错，hosts不够，请问该咋办？没找到相关的帖子

**Comment by yaya159456** [comment]
好像是因为这个host 是OFFLINE状态，请问怎么把它激活啊？

**Comment by yaya159456** [comment]
原来是因为配置文件没弄好，默认的127.0.0.1 需要修改……

**Comment by sanjinbro** [comment]
> 原来是因为配置文件没弄好，默认的127.0.0.1 需要修改……

您好，我目前也出现了这种情况，请问是修改哪个配置文件呢？

**Comment by wey-gu** [comment]
https://docs.nebula-graph.com.cn/3.2.0/20.appendix/0.FAQ/#host_not_enough
需要执行
`ADD HOSTS `
激活 storage hosts 哈

**Comment by sanjinbro** [comment]
> https://docs.nebula-graph.com.cn/3.2.0/20.appendix/0.FAQ/#host_not_enough 需要执行 `ADD HOSTS ` 激活 storage hosts 哈

天呐，我就是按照官方文档，先ADD HOSTS 然后把nebula-storaged.conf里面的local_ip改成了自己ADD的HOSTS，结果还是OFFLINE

**Comment by abby-cyber** [comment]
> 

重启服务试过了吗？https://docs.nebula-graph.com.cn/3.2.0/4.deployment-and-installation/manage-service/

**Comment by sanjinbro** [comment]
> > 
> 
> 重启服务试过了吗？https://docs.nebula-graph.com.cn/3.2.0/4.deployment-and-installation/manage-service/

重启完生效了，唉，我简直对自己的sb感到无语，谢谢大佬了

**Comment by sanjinbro** [comment]
> > 
> 
> 重启服务试过了吗？https://docs.nebula-graph.com.cn/3.2.0/4.deployment-and-installation/manage-service/

不好意思大哥，我重启完还是OFFLINE，刚才看错了 这可咋整啊
我目前做了以下工作：
1.把nebula-storaged.conf里面的local_ip改成了192.168.10.100（我自己虚拟机的ip）
2.使用命令：ADD HOSTS 192.168.10.100:9779
3.重启服务：/usr/local/nebula/scripts/nebula.service restart all
4.连接nebula：./nebula-console -addr 192.168.10.100 -port 9669 -u root -p nebula
结果show hosts的时候192.168.10.100还是OFFLINE

**Comment by sanjinbro** [comment]
> > 
> 
> 重启服务试过了吗？https://docs.nebula-graph.com.cn/3.2.0/4.deployment-and-installation/manage-service/

我这边把配置文件恢复成127.0.0.1 自己addhosts了127.0.0.1 目前是online的状态 可能单机版就只能这么配置吧

**Comment by wey-gu** [comment]
保证服务自己的 ip，服务配置的 meta 的 ip，在对应的端口上都能匹配上，都能通信。

可以看看 meta/storage 的log

**Comment by sanjinbro** [comment]
> 保证服务自己的 ip，服务配置的 meta 的 ip，在对应的端口上都能匹配上，都能通信。
> 
> 可以看看 meta/storage 的log

谢谢，我会详细看看的，导师这边突然要求我学习这个，我就比较心急，没有太细致。感谢解答！

**Comment by wey-gu** [comment]
> > 保证服务自己的 ip，服务配置的 meta 的 ip，在对应的端口上都能匹配上，都能通信。
> > 可以看看 meta/storage 的log
> 
> 谢谢，我会详细看看的，导师这边突然要求我学习这个，我就比较心急，没有太细致。感谢解答！

不要着急，仔细看看，可以贴一下配置、log 和实际网络的情况。

还有一点，如果 meta 不ready，storage 刚起来之后要过一会儿才能 online，不会特别频繁的 retry（联系 meta）
