### ISSUE TITLE
Exchange need to explain the difference between Enterprise and Opensource

### ISSUE THREAD

**Issue by nianiaJR** [vesoft-inc/nebula-docs-cn#2154]
As  I learned from practice, in most use case, I need to use the opensource edition instead of the enterprise, because the enterprise include only one feature which can use it to export the data from nebula, all the other rest features are in the opensource, it's a little confusing.

<img width="579" alt="image" src="https://user-images.githubusercontent.com/8124783/191404348-56909011-1b3e-4125-b73c-bb9511aef799.png">

**Comment by cooper-lzy** [comment]
Now the exchange has differentiated between community and enterprise editions, and the documents have been separated as well.
