### ISSUE TITLE
请教下mike的用法

### ISSUE THREAD

**Issue by longlongaxiang** [vesoft-inc/nebula-docs-cn#2180]
按照教程安装了mike插件并使用，mike deploy是成功的，也面也切分版本了，就是页面上不显示版本切换菜单，只能通过url切换。不知道是哪里没配置，我看mike的教程里再yaml里设置version selector 为true，我也尝试了，但是还是不显示
我看了你们这个工程，好像没有再yaml里写mike的参数呢，但是就是有版本切换菜单。

**Comment by whitewum** [comment]
你把它readme的例子本地先试试，别跳过里面的步骤。

**Comment by randomJoe211** [comment]
有生成version-selector.js吗，建议再看看mkdocs-material的官网文档，检查一下步骤细节，文档地址：
https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/

如果还不行，给他们提个issue问一下吧https://github.com/squidfunk/mkdocs-material/issues
