### ISSUE TITLE
Advice on quick start

### ISSUE THREAD

**Issue by SuperSupeng** [vesoft-inc/nebula-docs-cn#2200]
Suggest adding the docker method in the installation chapter of the quick start to help users to get started quickly. Note that RPM is recommended for production environments.

**Comment by wey-gu** [comment]
+1 agreed.

**Comment by randomJoe211** [comment]
We used to have the docker compose deployment doc in the quick start before doc version 2.5.0, but it turned out that installing with RPM/DEB/TAR has simpler steps and is more convenient for users. Hence we used the RPM installation in the quick start.

**Comment by SuperSupeng** [comment]
That is understandable, but what if I just want to use it on Mac or windows to test? 
Maybe add a link? It is a little complex to find a way to install using docker.

**Comment by wey-gu** [comment]
Ture, it's easier/ more straightforward for those with easy access to a Linux machine/server to install from binary packages yet easier for macOS/Windows-only users to access via Docker Desktop.

We could expose/highlight docker-compose a little bit more to enable first time coming/fresh user to be aware of the both.

**Comment by wey-gu** [comment]
How about something like this?

https://github.com/vesoft-inc/nebula-docs-cn/pull/2203

cc @randomJoe211 @SuperSupeng

**Comment by SuperSupeng** [comment]
LGTM

**Comment by whitewum** [comment]
If you'd like a lightweight trail, we prefer redirecting to the cloud service rather than a local docker. 
The cloud provides all products with visual tools, computing clusters, and operation management. But the docker doesn't, which only provides the db kernel and a console.
If you'd like to do a benchmark, refer to rpm.

**Comment by whitewum** [comment]
https://docs.nebula-graph.com.cn/3.1.0/nebula-cloud/1.what-is-cloud/
