### ISSUE TITLE
search in mobile

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2246]
We recently changed things(I am not sure, logo is wider than before?) to make the search box almost out of the screen, could we somehow bring it back?

![IMG_EE3DD3D82B02-1](https://user-images.githubusercontent.com/1651790/197448180-f0d7688f-eea0-4205-b830-6069c9f4c9d7.jpeg)

**Comment by randomJoe211** [comment]
The logo has not been modified for years, but the search box has recently been edited. Maybe that caused the issue.

**Comment by wey-gu** [comment]
cc @nianiaJR

**Comment by nianiaJR** [comment]
I'll check and fix it

**Comment by nianiaJR** [comment]
The key reason of this problem is that our nav has too many content and the logo is so long. So is it necessary to fix it in mobile?


![Image](https://user-images.githubusercontent.com/8124783/199645135-95deb159-2120-4d15-8297-273f1d0c7e4c.png)

**Comment by nianiaJR** [comment]
Think about more than 80% of users visit our docs via pc and most functions works well in mobile. So I suggest just keep the default theme style instead of modifying it.
