### ISSUE TITLE
add cloud chapter in recent versions

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2288]
like it was done in 3.3.0(although the cloud version is not 3.2.1), or user cannot search for cloud-related information in 3.2.1?

**Comment by whitewum** [comment]
OK. This is a test to see if cloud or on-premise is preferred. Just be patient for some time.

**Comment by whitewum** [comment]
I know this issue.

**Comment by abby-cyber** [comment]
close it as you can see the entrance of cloud docs in the latest version(3.3.0).
