### ISSUE TITLE
fav icon missing

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2294]
<img width="822" alt="Screen Shot 2022-11-03 at 10 23 22" src="https://user-images.githubusercontent.com/1651790/199636669-028c8adb-f804-4849-a3e6-7ec69b0532aa.png">

**Comment by randomJoe211** [comment]
Fixed in https://github.com/vesoft-inc/nebula-docs-cn/pull/2295

**Comment by wey-gu** [comment]
Could we change the logo width(ratio), too :)

https://github.com/vesoft-inc/nebula-docs-cn/issues/2246
