### ISSUE TITLE
文档好像没有介绍我们是否支持了麒麟等国产化 Linux？

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula-docs-cn#2346]
如题。确实没有的话，可以增加一下相关内容。

**Comment by abby-cyber** [comment]
> 如题。确实没有的话，可以增加一下相关内容。

麒麟的架构是基于 ARM ，企业版我们是支持的哈；社区版的支持限制文档里面有说明喔https://docs.nebula-graph.com.cn/master/4.deployment-and-installation/1.resource-preparations/#cpu 
![image](https://user-images.githubusercontent.com/78209557/203708026-35118fa1-e167-4c63-8b94-281ddd88d32e.png)

**Comment by wey-gu** [comment]
@abby-cyber 只是一个 ubuntu distribution 吧？和 ARM/X86 其实没有关系，也支持 X86_64 哈。

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2356/files

**Comment by abby-cyber** [comment]
only the enterprise version can be deployed on the nationalized Linux operating systems, see #2356
