### ISSUE TITLE
图计算 nebula-analytics内容里缺少免密提示

### ISSUE THREAD

**Issue by henry202108** [vesoft-inc/nebula-docs-cn#2625]
**Please check the FAQ documentation before raising an issue**

3.2之前都写了，3.3之后版本去掉了，这个是不能去掉的步骤
**Describe the bug (__required__)**
https://docs.nebula-graph.com.cn/3.3.0/graph-computing/nebula-analytics/

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by cooper-lzy** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/commit/6c0d29128cb1e864ca7a397030508df941696f36

**Comment by wey-gu** [comment]
master 最好加一下，否则下一个版本又缺了哈？

**Comment by cooper-lzy** [comment]
> 

等3.4文档稳定点，会把3.4的内容都merge到master，然后写新版本内容的。
