### ISSUE TITLE
Video in the document not play automatically

### ISSUE THREAD

**Issue by bazingame** [vesoft-inc/nebula-docs-cn#2628]
Can the video in the document not play automatically? For example, in the following document, eight or nine videos are played together after opening, which is unbearable.

https://docs.nebula-graph.com.cn/3.4.0/2.quick-start/1.quick-start-overview/

**Comment by wey-gu** [comment]
I agree with you! Would you mind pr to remove the auto play tag? Clicking the pencil on the top of the page will navigate you to the file.

**Comment by abby-cyber** [comment]
On my end, the videos are not playing all by default; they are in a paused state.

**Comment by QingZ11** [comment]
> Can the video in the document not play automatically? For example, in the following document, eight or nine videos are played together after opening, which is unbearable.
> 
> https://docs.nebula-graph.com.cn/3.4.0/2.quick-start/1.quick-start-overview/

谢谢你的反馈，这个问题在 https://github.com/vesoft-inc/nebula-docs/pull/2375 修复了，再次感谢 ❤️

Thank you for your feedback. This issue has been fixed in the [#PR](https://github.com/vesoft-inc/nebula-docs/pull/2375).
