### ISSUE TITLE
Unsupported nGQL grammar in Exchange doc

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula-docs-cn#2636]
**Please check the FAQ documentation before raising an issue**

In all the data source example pages, there's a note to use following nGQL to check imported data: `GO FROM "player100" OVER follow;`. However, this grammar is no longer supportted in NebulaGraph 3.x. "Yield" is required now.

![image](https://user-images.githubusercontent.com/6269380/223960957-6b53b2c9-5d54-4cee-a907-1385cec641d3.png)

**Describe the bug (__required__)**

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

**Expected behavior**

**Additional context**

**Comment by cooper-lzy** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2638
