### ISSUE TITLE
INSERT EDGE 语句的文档没有写 rank 的类型限制

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula-docs-cn#2650]
**Introduction**

`https://docs.nebula-graph.com.cn/3.4.1/3.ngql-guide/13.edge-statements/1.insert-edge/`
`rank：可选项。边的 rank 值。默认值为0。
`
未提示 rank 必须是 numeric 类型，不支持 string 等。

**Contents**

**Related work**

**Comment by cooper-lzy** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2665
