### ISSUE TITLE
“NebulaGraph 资源需求” 这一节需要澄清一些信息

### ISSUE THREAD

**Issue by xtcyclist** [vesoft-inc/nebula-docs-cn#2762]
https://docs.nebula-graph.com.cn/3.4.1/4.deployment-and-installation/1.resource-preparations/#nebulagraph_1

这部分文档需要说清楚：

1. 资源是指的是单机，还是整个集群总共？
2. 内存是指的 graphd 的内存，还是 storaged 的内存？

来源：
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/7731943/924d35cb-829e-45cd-970f-82304ec757dd)
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/7731943/0fcb7747-1485-42db-b2c3-c466f5462479)

**Comment by whitewum** [comment]
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/50101159/b7008243-2abb-4efe-9518-7f53b3645cde)
