### ISSUE TITLE
expose release note in index page/home page per each version of docs

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2791]
Users would expect to see what's added/new for a certain version of the release, they may not know the keyword: "release note" thus it could be hard for them to reach out to such chapter/info.

It'll be better to expose/highlight this in the index page of the doc.

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2807

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2807
