### ISSUE TITLE
Consider refactor FAQ doc

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2817]
Some of the chapters in FAQ are **Gold** and should be listed under other topics, i.e. the PORTS chapter should be under arch/system design, and the disk scale-up should be under the Ops/SRE chapter. We could keep the FAQ an index of key questions rather than a huge Bible.

Suggestion:
- move some of the FAQ chapters to other chapters(when applicable), but keep the question part, refer to its answer in corresponding chapters
- some content may deserve a standalone chapter, i.e. errors-and-solutions, when it's long enough yet there are no chapters to be moved to.

Benefits:
- Users will not easy to be lost in the giant FAQ docs
- They could see the corresponding content when reading corresponding doc chapters
- Better doc site search result/SEO, i.e., searching "扩容" didn't show the FAQ chapters now :(

ref: https://github.com/vesoft-inc/nebula-docs-cn/issues/2732

**Comment by abby-cyber** [comment]
Agreed, thank you for your advice. This is something we have been wanting to do. We are considering a redesign of our information architecture from version 5.0.
As for the site search result, yes, there seems to be an issue with the search engine.
