### ISSUE TITLE
Fulltext search limitation revisit

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2834]
Since 3.4.0, the fulltext search was refactored, thus some of the limitations are not valid, for example, the 256byte limitation.

We need to revisit and remove those invalid items https://docs.nebula-graph.com.cn/3.5.0/4.deployment-and-installation/6.deploy-text-based-index/1.text-based-index-restrictions/

We could double-check with @cangfengzhs when needed.

**Comment by abby-cyber** [comment]
fixed
