### ISSUE TITLE
Expose nebula-http-gateway in clients for docs

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2838]
I just realized we didn't highlight its existence, which could enable flexible frontend-oriented Graph Viz App development

https://docs.nebula-graph.com.cn/3.5.0/14.client/1.nebula-client/

**Comment by cooper-lzy** [comment]
Currently nebula-http-gateway is only used as a component of dashboard community edition, not as one of the clients for the time being, you can suggest it to the product department.
