### ISSUE TITLE
比较符中不应该包含算数运算符

### ISSUE THREAD

**Issue by shanlai** [vesoft-inc/nebula-docs-cn#2892]
<img width="1225" alt="image" src="https://github.com/vesoft-inc/nebula-docs-cn/assets/104358440/c56da1c9-d5cd-4e2b-9aca-68ad522eb279">

**Comment by abby-cyber** [comment]
https://github.com/vesoft-inc/nebula-docs-cn/pull/2894/files

**Comment by abby-cyber** [comment]
fixed
