### ISSUE TITLE
日期和时间类型支持的操作符描述不够清晰

### ISSUE THREAD

**Issue by shanlai** [vesoft-inc/nebula-docs-cn#2893]
当前支持的日期和时间类型有：DATE、TIME、DATETIME、TIMESTAMP和DURATION，但没有详细描述这些类型支持的操作符，希望能够丰富相关的描述并增加相关示例

**Comment by cooper-lzy** [comment]
和开发确认，当前时间日期的计算用duration函数，比较直观。我自己简单测了下，整数类型的加减只有date和timestamp支持，表示1天和1秒。修改文档建议用户使用duration。
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/78672629/615acb79-c58e-438b-b871-73a61771f388)

**Comment by abby-cyber** [comment]
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/78209557/d8e4e710-9fcd-4e15-953f-f90cb0efc832)
