### ISSUE TITLE
Error of memory tracker `GraphMemoryExceeded` should be mentioned

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2911]
Now if we search GraphMemoryExceeded there is no result in docs

**Comment by abby-cyber** [comment]
done https://github.com/vesoft-inc/nebula-docs-cn/pull/2917/files#diff-92795a083da1709107b98d364e315008ceaa8d4b4f8325c024be9870a2e4e5af

**Comment by wey-gu** [comment]
Thanks @abby-cyber !
