### ISSUE TITLE
添加num_operator_threads参数提高FIND PATH的查询性能，但[Graph 服务配置]中并没有该参数

### ISSUE THREAD

**Issue by CharleyXu** [vesoft-inc/nebula-docs-cn#2913]
<img width="1504" alt="image" src="https://github.com/vesoft-inc/nebula-docs-cn/assets/20060357/8f7ff694-83d8-49af-88e0-e7aaa08b1a01">
[Graph 服务配置]中并没有num_operator_threads参数

**Comment by abby-cyber** [comment]
> <img alt="image" width="1504" src="https://user-images.githubusercontent.com/20060357/254498472-8f7ff694-83d8-49af-88e0-e7aaa08b1a01.png"> [Graph 服务配置]中并没有num_operator_threads参数

【在`nebula-graph.conf`中**添加**`num_operator_threads`】是手动增加的意思喔，感谢反馈：）
