### ISSUE TITLE
[Exchange] 样例中的hadoop前提条件不应该是必须的

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula-docs-cn#2914]
**Please check the FAQ documentation before raising an issue**

**Describe the bug (__required__)**

例如：
https://docs.nebula-graph.com.cn/3.5.0/nebula-exchange/use-exchange/ex-ug-import-from-mysql/
在环境配置和前提条件中都要求hadoop，但实际上是不需要的。
其他数据源也类似，只有sst方式和导入hdfs文件的时候需要hadoop。
具体请和 @Nicole00 确认。

**Your Environments (__required__)**

* OS: `uname -a`
* Commit id (e.g. `a3ffc7d8`)

**How To Reproduce(__required__)**

1. Step 1
2. Step 2
3. Step 3

**Expected behavior**

**Additional context**

**Comment by cooper-lzy** [comment]
Thanks for your feedback, the documentation has been modified.
