### ISSUE TITLE
mention GeoSpatial(GIS) index in Index Creation(and other places)

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2927]
Our GeoSpatial can support index and then to do ST_* function calls as starting node.

This should be mentioned in Index Creation chapters.

ref: https://docs.nebula-graph.com.cn/3.5.0/3.ngql-guide/14.native-index-statements/1.create-native-index/
ref: https://docs.nebula-graph.com.cn/3.5.0/3.ngql-guide/3.data-types/10.geography/
```
CREATE TAG INDEX IF NOT EXISTS any_shape_geo_index ON place(geo_point);

# to enable such query

MATCH (sub:subscriber)-[:stays_in]->(place:place)
WHERE 
    ST_Distance(place.place.geo_point,
                ST_GeogFromText("POINT (121.5036 31.2974)")
                ) < 500
        AND
    sub.subscriber.birth > date("1998-12-31")
RETURN id(sub) AS id, sub.subscriber.name AS name, sub.subscriber.birth AS birth,
    "Student" AS profile
```

We could consdier adding
- MATCH examples in examples
- mentioning(description, reference to geospatial and add examples) geospatial index in index creation
  - one of the terms used normally is called "空间索引", We should mention this in docs to make user to search for it.

**Comment by cooper-lzy** [comment]
The documentation has changed the term names and added reference links, but has not added the example you provided because the example requires writing tck.
