### ISSUE TITLE
native log rotation

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2974]
NebulaGraph core instances came with builtin log rotation already, we should have a guide and conf explanation :-D

https://discuss.nebula-graph.com.cn/t/topic/13787/4?u=wey

**Comment by cooper-lzy** [comment]
After reading the replies at the end of the post, we can only use crontab to recycle log at the moment, first link to the solution in the FAQ in the logging docs, and then update the docs when support for using built-in parameters directly.

https://github.com/vesoft-inc/nebula-docs-cn/commit/192b2bff1aec8c0c44aceadc16771bd9e5263a06

**Comment by wey-gu** [comment]
Thanks! @cooper-lzy Let's wait for https://github.com/vesoft-inc/nebula/issues/5688 to enable further activities
