### ISSUE TITLE
add `-s` parameter on the configuration docs

### ISSUE THREAD

**Issue by abby-cyber** [vesoft-inc/nebula-docs-cn#2983]
https://docs.nebula-graph.io/3.4.2/5.configurations-and-logs/1.configurations/1.configurations/#get_configurations   
silent mode without progress display  `curl -s   127.0.0.1:19559/flags`

**Comment by shbone** [comment]
output is no difference between  `curl -s   127.0.0.1:19559/flags` and `curl    127.0.0.1:19559/flags`

with `-s ` parameter
``` bash
check_plan_killed_frequency=8
cluster_id_path="cluster.id"
expired_time_factor=2
failed_login_attempts=0
heartbeat_interval_secs=2
meta_client_retry_interval_secs=1
meta_client_retry_times=3
meta_client_timeout_ms=60000
password_lock_time_in_secs=0
enable_udf=0
udf_path="lib/udf"
log_disk_check_interval_secs=10
log_min_reserved_bytes_to_error=67108864
log_min_reserved_bytes_to_fatal=4194304
log_min_reserved_bytes_to_warn=268435456
cgroup_v1_memory_current_path="/sys/fs/cgroup/memory/memory.usage_in_bytes"
cgroup_v1_memory_max_path="/sys/fs/cgroup/memory/memory.limit_in_bytes"
cgroup_v1_memory_stat_path="/sys/fs/cgroup/memory/memory.stat"
cgroup_v2_controllers="/sys/fs/cgroup/cgroup.controllers"
cgroup_v2_memory_current_path="/sys/fs/cgroup/memory.current"
cgroup_v2_memory_max_path="/sys/fs/cgroup/memory.max"
cgroup_v2_memory_stat_path="/sys/fs/cgroup/memory.stat"
containerized=1
memory_purge_enabled=1
memory_purge_interval_seconds=10
memory_tracker_available_ratio=0.8
memory_tracker_detail_log=0
memory_tracker_detail_log_interval_ms=60000
memory_tracker_limit_ratio=0.8
memory_tracker_untracked_reserved_memory_mb=50
system_memory_high_watermark_ratio=0.8
gflags_mode_json="share/resources/gflags.json"
ca_path=""
cert_path=""
enable_graph_ssl=0
enable_meta_ssl=0
enable_ssl=0
key_path=""
password_path=""
conn_timeout_ms=1000
timezone_file="share/resources/date_time_zonespec.csv"
timezone_name="UTC+00:00:00"
daemonize=0
local_ip="172.28.1.1"
meta_http_thread_num=3
pid_file="pids/nebula-metad.pid"
port=9559
reuse_port=1
data_path="/data/meta"
meta_server_addrs="172.28.1.1:9559,172.28.1.2:9559,172.28.1.3:9559"
num_io_threads=16
num_worker_threads=32
redirect_stdout=1
stderr_log_file="metad-stderr.log"
stdout_log_file="metad-stdout.log"
disk_check_interval_secs=10
minimum_reserved_bytes=1073741824
snapshot_batch_size=524288
snapshot_part_rate_limit=10485760
auto_remove_invalid_space=1
clean_wal_interval_secs=600
engine_type="rocksdb"
num_workers=4
cluster_id=0
skip_wait_in_rate_limiter=0
balance_expired_sesc=86400
move_files=0
cache_bucket_exp=8
disable_page_cache=0
enable_partitioned_index_filter=0
enable_rocksdb_prefix_filtering=1
enable_rocksdb_statistics=0
enable_rocksdb_whole_key_filtering=0
num_compaction_threads=0
rocksdb_backup_dir=""
rocksdb_backup_interval_secs=300
rocksdb_batch_size=4096
rocksdb_blob_compression="snappy"
rocksdb_block_based_table_options="{}"
rocksdb_block_cache=1024
rocksdb_bottommost_compression="disable"
rocksdb_column_family_options="{}"
rocksdb_compact_change_level=1
rocksdb_compact_target_level=-1
rocksdb_compression="snappy"
rocksdb_compression_per_level=""
rocksdb_db_options="{}"
rocksdb_disable_wal=0
rocksdb_enable_blob_garbage_collection=1
rocksdb_enable_kv_separation=0
rocksdb_kv_separation_threshold=100
rocksdb_rate_limit=0
rocksdb_row_cache_num=16000000
rocksdb_stats_level="kExceptHistogramOrTimers"
rocksdb_table_format="BlockBasedTable"
rocksdb_wal_dir=""
rocksdb_wal_sync=0
ft_bulk_batch_size=100
ft_request_retry_times=3
listener_commit_interval_secs=1
listener_pursue_leader_threshold=1000
listener_commit_batch_size=1000
max_appendlog_batch_size=128
max_outstanding_requests=1024
pause_host_time_factor=4
raft_rpc_timeout_ms=1000
max_batch_size=256
raft_heartbeat_interval_secs=5
raft_snapshot_timeout=300
trace_raft=0
snapshot_io_threads=4
snapshot_send_retry_times=3
snapshot_send_timeout_ms=60000
snapshot_worker_threads=4
max_log_buffer_size=16777216
wal_buffer_size=8388608
wal_file_size=16777216
wal_sync=0
wal_ttl=14400
agent_heartbeat_interval_secs=60
null_type=1
print_info=0
string_index_limit=64
max_retry_times_admin_op=30
client_white_list="2023.09.26-nightly:3.0.0"
enable_client_white_list=1
task_concurrency=10
job_check_intervals=5000
job_expired_secs=604800
job_threads=10
leader_balance_deviation=0.05
default_parts_num=100
default_replica_factor=1
removed_threshold_sec=86400
ws_http_port=19559
ws_ip="172.28.1.1"
ws_threads=4
codel_enabled=0
thrift_cpp2_protocol_reader_container_limit=0
thrift_cpp2_protocol_reader_string_limit=0
thrift_server_request_debug_log_entries_max=10000
service_identity=""
thrift_abort_if_exceeds_shutdown_deadline=1
thrift_ssl_policy="disabled"
folly_memory_idler_purge_arenas=1
dynamic_cputhreadpoolexecutor=1
codel_interval=100
codel_target_delay=5
dynamic_iothreadpoolexecutor=1
threadtimeout_ms=60000
observer_manager_pool_size=4
logging=""
folly_hazptr_use_executor=1
flagfile="/usr/local/nebula/etc/nebula-metad.conf"
fromenv=""
tryfromenv=""
undefok=""
tab_completion_columns=80
tab_completion_word=""
help=0
helpfull=0
helpmatch=""
helpon=""
helppackage=0
helpshort=0
helpxml=0
version=0
alsologtoemail=""
alsologtostderr=0
colorlogtostderr=0
drop_log_memory=1
log_backtrace_at=""
log_dir="/logs"
log_link=""
log_prefix=1
log_utc_time=0
logbuflevel=0
logbufsecs=0
logemaillevel=999
logfile_mode=436
logmailer=""
logtostderr=0
max_log_size=1800
minloglevel=0
stderrthreshold=0
stop_logging_if_full_disk=0
timestamp_in_logfile_name=1
symbolize_stacktrace=1
v=0
vmodule=""
zlib_compressor_buffer_growth=2024
s2shape_index_cell_size_to_long_edge_ratio=1
s2shape_index_default_max_edges_per_cell=10
s2shape_index_tmp_memory_budget_mb=100
s2cell_union_decode_max_num_cells=1000000
s2debug=0
s2loop_lazy_indexing=1
s2polygon_decode_max_num_vertices=50000000
s2polygon_decode_max_num_loops=10000000
s2polygon_lazy_indexing=1
dcache_unit_test=0
```


without `-s` parameter
```bash
check_plan_killed_frequency=8
cluster_id_path="cluster.id"
expired_time_factor=2
failed_login_attempts=0
heartbeat_interval_secs=2
meta_client_retry_interval_secs=1
meta_client_retry_times=3
meta_client_timeout_ms=60000
password_lock_time_in_secs=0
enable_udf=0
udf_path="lib/udf"
log_disk_check_interval_secs=10
log_min_reserved_bytes_to_error=67108864
log_min_reserved_bytes_to_fatal=4194304
log_min_reserved_bytes_to_warn=268435456
cgroup_v1_memory_current_path="/sys/fs/cgroup/memory/memory.usage_in_bytes"
cgroup_v1_memory_max_path="/sys/fs/cgroup/memory/memory.limit_in_bytes"
cgroup_v1_memory_stat_path="/sys/fs/cgroup/memory/memory.stat"
cgroup_v2_controllers="/sys/fs/cgroup/cgroup.controllers"
cgroup_v2_memory_current_path="/sys/fs/cgroup/memory.current"
cgroup_v2_memory_max_path="/sys/fs/cgroup/memory.max"
cgroup_v2_memory_stat_path="/sys/fs/cgroup/memory.stat"
containerized=1
memory_purge_enabled=1
memory_purge_interval_seconds=10
memory_tracker_available_ratio=0.8
memory_tracker_detail_log=0
memory_tracker_detail_log_interval_ms=60000
memory_tracker_limit_ratio=0.8
memory_tracker_untracked_reserved_memory_mb=50
system_memory_high_watermark_ratio=0.8
gflags_mode_json="share/resources/gflags.json"
ca_path=""
cert_path=""
enable_graph_ssl=0
enable_meta_ssl=0
enable_ssl=0
key_path=""
password_path=""
conn_timeout_ms=1000
timezone_file="share/resources/date_time_zonespec.csv"
timezone_name="UTC+00:00:00"
daemonize=0
local_ip="172.28.1.1"
meta_http_thread_num=3
pid_file="pids/nebula-metad.pid"
port=9559
reuse_port=1
data_path="/data/meta"
meta_server_addrs="172.28.1.1:9559,172.28.1.2:9559,172.28.1.3:9559"
num_io_threads=16
num_worker_threads=32
redirect_stdout=1
stderr_log_file="metad-stderr.log"
stdout_log_file="metad-stdout.log"
disk_check_interval_secs=10
minimum_reserved_bytes=1073741824
snapshot_batch_size=524288
snapshot_part_rate_limit=10485760
auto_remove_invalid_space=1
clean_wal_interval_secs=600
engine_type="rocksdb"
num_workers=4
cluster_id=0
skip_wait_in_rate_limiter=0
balance_expired_sesc=86400
move_files=0
cache_bucket_exp=8
disable_page_cache=0
enable_partitioned_index_filter=0
enable_rocksdb_prefix_filtering=1
enable_rocksdb_statistics=0
enable_rocksdb_whole_key_filtering=0
num_compaction_threads=0
rocksdb_backup_dir=""
rocksdb_backup_interval_secs=300
rocksdb_batch_size=4096
rocksdb_blob_compression="snappy"
rocksdb_block_based_table_options="{}"
rocksdb_block_cache=1024
rocksdb_bottommost_compression="disable"
rocksdb_column_family_options="{}"
rocksdb_compact_change_level=1
rocksdb_compact_target_level=-1
rocksdb_compression="snappy"
rocksdb_compression_per_level=""
rocksdb_db_options="{}"
rocksdb_disable_wal=0
rocksdb_enable_blob_garbage_collection=1
rocksdb_enable_kv_separation=0
rocksdb_kv_separation_threshold=100
rocksdb_rate_limit=0
rocksdb_row_cache_num=16000000
rocksdb_stats_level="kExceptHistogramOrTimers"
rocksdb_table_format="BlockBasedTable"
rocksdb_wal_dir=""
rocksdb_wal_sync=0
ft_bulk_batch_size=100
ft_request_retry_times=3
listener_commit_interval_secs=1
listener_pursue_leader_threshold=1000
listener_commit_batch_size=1000
max_appendlog_batch_size=128
max_outstanding_requests=1024
pause_host_time_factor=4
raft_rpc_timeout_ms=1000
max_batch_size=256
raft_heartbeat_interval_secs=5
raft_snapshot_timeout=300
trace_raft=0
snapshot_io_threads=4
snapshot_send_retry_times=3
snapshot_send_timeout_ms=60000
snapshot_worker_threads=4
max_log_buffer_size=16777216
wal_buffer_size=8388608
wal_file_size=16777216
wal_sync=0
wal_ttl=14400
agent_heartbeat_interval_secs=60
null_type=1
print_info=0
string_index_limit=64
max_retry_times_admin_op=30
client_white_list="2023.09.26-nightly:3.0.0"
enable_client_white_list=1
task_concurrency=10
job_check_intervals=5000
job_expired_secs=604800
job_threads=10
leader_balance_deviation=0.05
default_parts_num=100
default_replica_factor=1
removed_threshold_sec=86400
ws_http_port=19559
ws_ip="172.28.1.1"
ws_threads=4
codel_enabled=0
thrift_cpp2_protocol_reader_container_limit=0
thrift_cpp2_protocol_reader_string_limit=0
thrift_server_request_debug_log_entries_max=10000
service_identity=""
thrift_abort_if_exceeds_shutdown_deadline=1
thrift_ssl_policy="disabled"
folly_memory_idler_purge_arenas=1
dynamic_cputhreadpoolexecutor=1
codel_interval=100
codel_target_delay=5
dynamic_iothreadpoolexecutor=1
threadtimeout_ms=60000
observer_manager_pool_size=4
logging=""
folly_hazptr_use_executor=1
flagfile="/usr/local/nebula/etc/nebula-metad.conf"
fromenv=""
tryfromenv=""
undefok=""
tab_completion_columns=80
tab_completion_word=""
help=0
helpfull=0
helpmatch=""
helpon=""
helppackage=0
helpshort=0
helpxml=0
version=0
alsologtoemail=""
alsologtostderr=0
colorlogtostderr=0
drop_log_memory=1
log_backtrace_at=""
log_dir="/logs"
log_link=""
log_prefix=1
log_utc_time=0
logbuflevel=0
logbufsecs=0
logemaillevel=999
logfile_mode=436
logmailer=""
logtostderr=0
max_log_size=1800
minloglevel=0
stderrthreshold=0
stop_logging_if_full_disk=0
timestamp_in_logfile_name=1
symbolize_stacktrace=1
v=0
vmodule=""
zlib_compressor_buffer_growth=2024
s2shape_index_cell_size_to_long_edge_ratio=1
s2shape_index_default_max_edges_per_cell=10
s2shape_index_tmp_memory_budget_mb=100
s2cell_union_decode_max_num_cells=1000000
s2debug=0
s2loop_lazy_indexing=1
s2polygon_decode_max_num_vertices=50000000
s2polygon_decode_max_num_loops=10000000
s2polygon_lazy_indexing=1
dcache_unit_test=0
```

**Comment by abby-cyber** [comment]
> hello, do you mean this work is to edit this command `curl -s 127.0.0.1:19559/flags` without showing other information? @abby-cyber Thank you!

Yes, exectly. The `-s` option is added to eradicate progress indicators and error messages. You can see the diff from the below pics.

![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/78209557/19efdd71-61f5-4f59-8af0-a7e12b699c89)
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/78209557/76ad180f-9595-486a-b6cb-12aec6d78bf5)

**Comment by abby-cyber** [comment]
> output is no difference between `curl -s 127.0.0.1:19559/flags` and `curl 127.0.0.1:19559/flags`
> 
> with `-s ` parameter
> 
> ```shell
> check_plan_killed_frequency=8
> cluster_id_path="cluster.id"
> expired_time_factor=2
> failed_login_attempts=0
> heartbeat_interval_secs=2
> meta_client_retry_interval_secs=1
> meta_client_retry_times=3
> meta_client_timeout_ms=60000
> password_lock_time_in_secs=0
> enable_udf=0
> udf_path="lib/udf"
> log_disk_check_interval_secs=10
> log_min_reserved_bytes_to_error=67108864
> log_min_reserved_bytes_to_fatal=4194304
> log_min_reserved_bytes_to_warn=268435456
> cgroup_v1_memory_current_path="/sys/fs/cgroup/memory/memory.usage_in_bytes"
> cgroup_v1_memory_max_path="/sys/fs/cgroup/memory/memory.limit_in_bytes"
> cgroup_v1_memory_stat_path="/sys/fs/cgroup/memory/memory.stat"
> cgroup_v2_controllers="/sys/fs/cgroup/cgroup.controllers"
> cgroup_v2_memory_current_path="/sys/fs/cgroup/memory.current"
> cgroup_v2_memory_max_path="/sys/fs/cgroup/memory.max"
> cgroup_v2_memory_stat_path="/sys/fs/cgroup/memory.stat"
> containerized=1
> memory_purge_enabled=1
> memory_purge_interval_seconds=10
> memory_tracker_available_ratio=0.8
> memory_tracker_detail_log=0
> memory_tracker_detail_log_interval_ms=60000
> memory_tracker_limit_ratio=0.8
> memory_tracker_untracked_reserved_memory_mb=50
> system_memory_high_watermark_ratio=0.8
> gflags_mode_json="share/resources/gflags.json"
> ca_path=""
> cert_path=""
> enable_graph_ssl=0
> enable_meta_ssl=0
> enable_ssl=0
> key_path=""
> password_path=""
> conn_timeout_ms=1000
> timezone_file="share/resources/date_time_zonespec.csv"
> timezone_name="UTC+00:00:00"
> daemonize=0
> local_ip="172.28.1.1"
> meta_http_thread_num=3
> pid_file="pids/nebula-metad.pid"
> port=9559
> reuse_port=1
> data_path="/data/meta"
> meta_server_addrs="172.28.1.1:9559,172.28.1.2:9559,172.28.1.3:9559"
> num_io_threads=16
> num_worker_threads=32
> redirect_stdout=1
> stderr_log_file="metad-stderr.log"
> stdout_log_file="metad-stdout.log"
> disk_check_interval_secs=10
> minimum_reserved_bytes=1073741824
> snapshot_batch_size=524288
> snapshot_part_rate_limit=10485760
> auto_remove_invalid_space=1
> clean_wal_interval_secs=600
> engine_type="rocksdb"
> num_workers=4
> cluster_id=0
> skip_wait_in_rate_limiter=0
> balance_expired_sesc=86400
> move_files=0
> cache_bucket_exp=8
> disable_page_cache=0
> enable_partitioned_index_filter=0
> enable_rocksdb_prefix_filtering=1
> enable_rocksdb_statistics=0
> enable_rocksdb_whole_key_filtering=0
> num_compaction_threads=0
> rocksdb_backup_dir=""
> rocksdb_backup_interval_secs=300
> rocksdb_batch_size=4096
> rocksdb_blob_compression="snappy"
> rocksdb_block_based_table_options="{}"
> rocksdb_block_cache=1024
> rocksdb_bottommost_compression="disable"
> rocksdb_column_family_options="{}"
> rocksdb_compact_change_level=1
> rocksdb_compact_target_level=-1
> rocksdb_compression="snappy"
> rocksdb_compression_per_level=""
> rocksdb_db_options="{}"
> rocksdb_disable_wal=0
> rocksdb_enable_blob_garbage_collection=1
> rocksdb_enable_kv_separation=0
> rocksdb_kv_separation_threshold=100
> rocksdb_rate_limit=0
> rocksdb_row_cache_num=16000000
> rocksdb_stats_level="kExceptHistogramOrTimers"
> rocksdb_table_format="BlockBasedTable"
> rocksdb_wal_dir=""
> rocksdb_wal_sync=0
> ft_bulk_batch_size=100
> ft_request_retry_times=3
> listener_commit_interval_secs=1
> listener_pursue_leader_threshold=1000
> listener_commit_batch_size=1000
> max_appendlog_batch_size=128
> max_outstanding_requests=1024
> pause_host_time_factor=4
> raft_rpc_timeout_ms=1000
> max_batch_size=256
> raft_heartbeat_interval_secs=5
> raft_snapshot_timeout=300
> trace_raft=0
> snapshot_io_threads=4
> snapshot_send_retry_times=3
> snapshot_send_timeout_ms=60000
> snapshot_worker_threads=4
> max_log_buffer_size=16777216
> wal_buffer_size=8388608
> wal_file_size=16777216
> wal_sync=0
> wal_ttl=14400
> agent_heartbeat_interval_secs=60
> null_type=1
> print_info=0
> string_index_limit=64
> max_retry_times_admin_op=30
> client_white_list="2023.09.26-nightly:3.0.0"
> enable_client_white_list=1
> task_concurrency=10
> job_check_intervals=5000
> job_expired_secs=604800
> job_threads=10
> leader_balance_deviation=0.05
> default_parts_num=100
> default_replica_factor=1
> removed_threshold_sec=86400
> ws_http_port=19559
> ws_ip="172.28.1.1"
> ws_threads=4
> codel_enabled=0
> thrift_cpp2_protocol_reader_container_limit=0
> thrift_cpp2_protocol_reader_string_limit=0
> thrift_server_request_debug_log_entries_max=10000
> service_identity=""
> thrift_abort_if_exceeds_shutdown_deadline=1
> thrift_ssl_policy="disabled"
> folly_memory_idler_purge_arenas=1
> dynamic_cputhreadpoolexecutor=1
> codel_interval=100
> codel_target_delay=5
> dynamic_iothreadpoolexecutor=1
> threadtimeout_ms=60000
> observer_manager_pool_size=4
> logging=""
> folly_hazptr_use_executor=1
> flagfile="/usr/local/nebula/etc/nebula-metad.conf"
> fromenv=""
> tryfromenv=""
> undefok=""
> tab_completion_columns=80
> tab_completion_word=""
> help=0
> helpfull=0
> helpmatch=""
> helpon=""
> helppackage=0
> helpshort=0
> helpxml=0
> version=0
> alsologtoemail=""
> alsologtostderr=0
> colorlogtostderr=0
> drop_log_memory=1
> log_backtrace_at=""
> log_dir="/logs"
> log_link=""
> log_prefix=1
> log_utc_time=0
> logbuflevel=0
> logbufsecs=0
> logemaillevel=999
> logfile_mode=436
> logmailer=""
> logtostderr=0
> max_log_size=1800
> minloglevel=0
> stderrthreshold=0
> stop_logging_if_full_disk=0
> timestamp_in_logfile_name=1
> symbolize_stacktrace=1
> v=0
> vmodule=""
> zlib_compressor_buffer_growth=2024
> s2shape_index_cell_size_to_long_edge_ratio=1
> s2shape_index_default_max_edges_per_cell=10
> s2shape_index_tmp_memory_budget_mb=100
> s2cell_union_decode_max_num_cells=1000000
> s2debug=0
> s2loop_lazy_indexing=1
> s2polygon_decode_max_num_vertices=50000000
> s2polygon_decode_max_num_loops=10000000
> s2polygon_lazy_indexing=1
> dcache_unit_test=0
> ```
> 
> without `-s` parameter
> 
> ```shell
> check_plan_killed_frequency=8
> cluster_id_path="cluster.id"
> expired_time_factor=2
> failed_login_attempts=0
> heartbeat_interval_secs=2
> meta_client_retry_interval_secs=1
> meta_client_retry_times=3
> meta_client_timeout_ms=60000
> password_lock_time_in_secs=0
> enable_udf=0
> udf_path="lib/udf"
> log_disk_check_interval_secs=10
> log_min_reserved_bytes_to_error=67108864
> log_min_reserved_bytes_to_fatal=4194304
> log_min_reserved_bytes_to_warn=268435456
> cgroup_v1_memory_current_path="/sys/fs/cgroup/memory/memory.usage_in_bytes"
> cgroup_v1_memory_max_path="/sys/fs/cgroup/memory/memory.limit_in_bytes"
> cgroup_v1_memory_stat_path="/sys/fs/cgroup/memory/memory.stat"
> cgroup_v2_controllers="/sys/fs/cgroup/cgroup.controllers"
> cgroup_v2_memory_current_path="/sys/fs/cgroup/memory.current"
> cgroup_v2_memory_max_path="/sys/fs/cgroup/memory.max"
> cgroup_v2_memory_stat_path="/sys/fs/cgroup/memory.stat"
> containerized=1
> memory_purge_enabled=1
> memory_purge_interval_seconds=10
> memory_tracker_available_ratio=0.8
> memory_tracker_detail_log=0
> memory_tracker_detail_log_interval_ms=60000
> memory_tracker_limit_ratio=0.8
> memory_tracker_untracked_reserved_memory_mb=50
> system_memory_high_watermark_ratio=0.8
> gflags_mode_json="share/resources/gflags.json"
> ca_path=""
> cert_path=""
> enable_graph_ssl=0
> enable_meta_ssl=0
> enable_ssl=0
> key_path=""
> password_path=""
> conn_timeout_ms=1000
> timezone_file="share/resources/date_time_zonespec.csv"
> timezone_name="UTC+00:00:00"
> daemonize=0
> local_ip="172.28.1.1"
> meta_http_thread_num=3
> pid_file="pids/nebula-metad.pid"
> port=9559
> reuse_port=1
> data_path="/data/meta"
> meta_server_addrs="172.28.1.1:9559,172.28.1.2:9559,172.28.1.3:9559"
> num_io_threads=16
> num_worker_threads=32
> redirect_stdout=1
> stderr_log_file="metad-stderr.log"
> stdout_log_file="metad-stdout.log"
> disk_check_interval_secs=10
> minimum_reserved_bytes=1073741824
> snapshot_batch_size=524288
> snapshot_part_rate_limit=10485760
> auto_remove_invalid_space=1
> clean_wal_interval_secs=600
> engine_type="rocksdb"
> num_workers=4
> cluster_id=0
> skip_wait_in_rate_limiter=0
> balance_expired_sesc=86400
> move_files=0
> cache_bucket_exp=8
> disable_page_cache=0
> enable_partitioned_index_filter=0
> enable_rocksdb_prefix_filtering=1
> enable_rocksdb_statistics=0
> enable_rocksdb_whole_key_filtering=0
> num_compaction_threads=0
> rocksdb_backup_dir=""
> rocksdb_backup_interval_secs=300
> rocksdb_batch_size=4096
> rocksdb_blob_compression="snappy"
> rocksdb_block_based_table_options="{}"
> rocksdb_block_cache=1024
> rocksdb_bottommost_compression="disable"
> rocksdb_column_family_options="{}"
> rocksdb_compact_change_level=1
> rocksdb_compact_target_level=-1
> rocksdb_compression="snappy"
> rocksdb_compression_per_level=""
> rocksdb_db_options="{}"
> rocksdb_disable_wal=0
> rocksdb_enable_blob_garbage_collection=1
> rocksdb_enable_kv_separation=0
> rocksdb_kv_separation_threshold=100
> rocksdb_rate_limit=0
> rocksdb_row_cache_num=16000000
> rocksdb_stats_level="kExceptHistogramOrTimers"
> rocksdb_table_format="BlockBasedTable"
> rocksdb_wal_dir=""
> rocksdb_wal_sync=0
> ft_bulk_batch_size=100
> ft_request_retry_times=3
> listener_commit_interval_secs=1
> listener_pursue_leader_threshold=1000
> listener_commit_batch_size=1000
> max_appendlog_batch_size=128
> max_outstanding_requests=1024
> pause_host_time_factor=4
> raft_rpc_timeout_ms=1000
> max_batch_size=256
> raft_heartbeat_interval_secs=5
> raft_snapshot_timeout=300
> trace_raft=0
> snapshot_io_threads=4
> snapshot_send_retry_times=3
> snapshot_send_timeout_ms=60000
> snapshot_worker_threads=4
> max_log_buffer_size=16777216
> wal_buffer_size=8388608
> wal_file_size=16777216
> wal_sync=0
> wal_ttl=14400
> agent_heartbeat_interval_secs=60
> null_type=1
> print_info=0
> string_index_limit=64
> max_retry_times_admin_op=30
> client_white_list="2023.09.26-nightly:3.0.0"
> enable_client_white_list=1
> task_concurrency=10
> job_check_intervals=5000
> job_expired_secs=604800
> job_threads=10
> leader_balance_deviation=0.05
> default_parts_num=100
> default_replica_factor=1
> removed_threshold_sec=86400
> ws_http_port=19559
> ws_ip="172.28.1.1"
> ws_threads=4
> codel_enabled=0
> thrift_cpp2_protocol_reader_container_limit=0
> thrift_cpp2_protocol_reader_string_limit=0
> thrift_server_request_debug_log_entries_max=10000
> service_identity=""
> thrift_abort_if_exceeds_shutdown_deadline=1
> thrift_ssl_policy="disabled"
> folly_memory_idler_purge_arenas=1
> dynamic_cputhreadpoolexecutor=1
> codel_interval=100
> codel_target_delay=5
> dynamic_iothreadpoolexecutor=1
> threadtimeout_ms=60000
> observer_manager_pool_size=4
> logging=""
> folly_hazptr_use_executor=1
> flagfile="/usr/local/nebula/etc/nebula-metad.conf"
> fromenv=""
> tryfromenv=""
> undefok=""
> tab_completion_columns=80
> tab_completion_word=""
> help=0
> helpfull=0
> helpmatch=""
> helpon=""
> helppackage=0
> helpshort=0
> helpxml=0
> version=0
> alsologtoemail=""
> alsologtostderr=0
> colorlogtostderr=0
> drop_log_memory=1
> log_backtrace_at=""
> log_dir="/logs"
> log_link=""
> log_prefix=1
> log_utc_time=0
> logbuflevel=0
> logbufsecs=0
> logemaillevel=999
> logfile_mode=436
> logmailer=""
> logtostderr=0
> max_log_size=1800
> minloglevel=0
> stderrthreshold=0
> stop_logging_if_full_disk=0
> timestamp_in_logfile_name=1
> symbolize_stacktrace=1
> v=0
> vmodule=""
> zlib_compressor_buffer_growth=2024
> s2shape_index_cell_size_to_long_edge_ratio=1
> s2shape_index_default_max_edges_per_cell=10
> s2shape_index_tmp_memory_budget_mb=100
> s2cell_union_decode_max_num_cells=1000000
> s2debug=0
> s2loop_lazy_indexing=1
> s2polygon_decode_max_num_vertices=50000000
> s2polygon_decode_max_num_loops=10000000
> s2polygon_lazy_indexing=1
> dcache_unit_test=0
> ```

Maybe the request is too swift to see the progress bar.
