### ISSUE TITLE
importer(v4) add highlight/notes on delimiter

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#2987]
i.e. the `\t` should be put as "\t" rather than '\t', the latter means "\\\t".

cc @veezhang

**Comment by veezhang** [comment]
https://stackoverflow.com/questions/19109912/yaml-do-i-need-quotes-for-strings-in-yaml

**Comment by shbone** [comment]
what this task mean? edit yaml document delimiter  to the better format? i.e. '\n' to "\n"

**Comment by wey-gu** [comment]
Add highlights that when \t is the dilmeter we should use ' to quote.
