### ISSUE TITLE
中文文档描述错误

### ISSUE THREAD

**Issue by zh19990906** [vesoft-inc/nebula-docs-cn#3071]
![image](https://github.com/vesoft-inc/nebula-docs-cn/assets/59323683/ba8d8946-b702-4a01-91a4-06d4d2144afc)
描述错误，应该是选择创建好的图空间。

**Comment by abby-cyber** [comment]
Good catch! Thank you!
FYI: The most recent version is exclusively modified. Changes have been made to the latest version. https://github.com/vesoft-inc/nebula-docs/pull/2370
