### ISSUE TITLE
进入文档自动播放视频，一次3、4个视频同时播放，优化下吧

### ISSUE THREAD

**Issue by papandadj** [vesoft-inc/nebula-docs-cn#3072]
进入文档，自己就开始播放视频了，https://docs.nebula-graph.com.cn/3.6.0/1.introduction/1.what-is-nebula-graph/  有的文档好几个视频，进去后全部开始播放，你们在刷播放量吧

**Comment by wey-gu** [comment]
> 你们在刷播放量吧

I don't think so, and we don't do/care about dirty things like that, the embedding iframe is not explicitly being added with auto-play-related arguments:

```
<iframe src="//player.bilibili.com/player.html?aid=287936425&bvid=BV1kf4y1v7LM&cid=259888281&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="720px" height="480px"> </iframe>
```

@ChrisChen2023 

We should consider disabling the auto-play of Bilibili videos.

Seems this is the way to go, by adding `&autoplay=0` :
```diff
- <iframe src="//player.bilibili.com/player.html?aid=287936425&bvid=BV1kf4y1v7LM&cid=259888281&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="720px" height="480px"> </iframe>
+ <iframe src="//player.bilibili.com/player.html?aid=287936425&bvid=BV1kf4y1v7LM&cid=259888281&autoplay=0&page=1" scrolling="no" border="0" frameborder="no" framespacing="0" allowfullscreen="true" width="720px" height="480px"> </iframe>
```

**Comment by papandadj** [comment]
说刷播放量就开个玩笑，并没有其他脏不脏的意思，感谢作出这么好的项目

**Comment by QingZ11** [comment]
> 说刷播放量就开个玩笑，并没有其他脏不脏的意思，感谢作出这么好的项目

非常感谢你的反馈~
