### ISSUE TITLE
[Format]: indented fenced code blocks escaped by basic code blocks

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#366]
It's found some backticks fenced code blocks under the `-` separated lists were indented.

For the reason indentation itself is [the semantics of the basic code block](https://www.markdownguide.org/basic-syntax#code-blocks), thus the [backticks fenced code blocks](https://www.markdownguide.org/extended-syntax/#fenced-code-blocks) will end up being escaped like below [Example 0], also a PR #367 was created, could you please help see if it's the way to fix this(sorry, I didn't try it via `mkdocs` yet)?

> Rendered Example 0
![Renderred Example 0](https://user-images.githubusercontent.com/1651790/116981855-a978cd80-acfa-11eb-9c39-5dff26f47a26.png)

> Example 0
```markdown
2. 检查主机上的GCC和CMake版本是否正确。版本信息请参见[软件要求](#_4)。

    ```bash
    $ g++ --version
    $ cmake --version
    ```

    如果版本正确，您可以跳过本小节。如果不正确，请根据如下步骤安装：

    1. 克隆仓库`nebula-common`到主机。

        ```bash
        $ git clone https://github.com/vesoft-inc/nebula-common.git
        ```

        类似{{ nebula.release }}版本的Nebula Graph源码存储在特定的分支，您可以使用`--branch`或`-b`选项指定克隆的分支。例如指定{{ nebula.release }}，命令如下：

        ```bash
        $ git clone --branch v{{ nebula.release }} https://github.com/vesoft-inc/nebula-common.git
        ```

    2. 进入目录`nebula-common`。

        ```bash
        $ cd nebula-common
        ```
```
> Proposed Change would be to remove the indentation, which is not yet verified.

```diff
diff --git a/docs-2.0/4.deployment-and-installation/1.resource-preparations.md b/docs-2.0/4.deployment-and-installation/1.resource-preparations.md
index ea083e7e..c68dbdae 100644
--- a/docs-2.0/4.deployment-and-installation/1.resource-preparations.md
+++ b/docs-2.0/4.deployment-and-installation/1.resource-preparations.md
@@ -114,36 +114,37 @@

     1. 克隆仓库`nebula-common`到主机。

-        ```bash
-        $ git clone https://github.com/vesoft-inc/nebula-common.git
-        ```
+    ```bash
+    $ git clone https://github.com/vesoft-inc/nebula-common.git
+    ```

```

Related Doc Pages:
- https://docs.nebula-graph.com.cn/2.0.1/4.deployment-and-installation/1.resource-preparations/
- https://docs.nebula-graph.com.cn/2.0.1/4.deployment-and-installation/2.compile-and-install-nebula-graph/1.install-nebula-graph-by-compiling-the-source-code/

**Comment by wey-gu** [comment]
BTW. The equivalent change should be applied to the English doc, too. @randomJoe211  :-D

https://docs.nebula-graph.io/2.0.1/4.deployment-and-installation/1.resource-preparations/

**Comment by wey-gu** [comment]
Also, some other code block not rendered as expected :-) 

https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/3.data-types/3.string/

**Comment by whitewum** [comment]
> Also, some other code block not rendered as expected :-)
> 
> https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/3.data-types/3.string/

Good catch. can you help to fix this. Yyou can click on the `pencil/edit button` and edit it directly.
