### ISSUE TITLE
Functions to be exposed in Doc

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#369]
This was triggered by @Shylock-Hg, who shared the function `datasetrowcol()` in the forum, thanks @Shylock-Hg !!!

Should we review new functions that are worth exposing to end-users?

ref: https://github.com/vesoft-inc/nebula-common/blob/master/src/common/function/FunctionManager.cpp

Thanks!

**Comment by cooper-lzy** [comment]
Maybe it needs to be decided by the PM/PD.

**Comment by whitewum** [comment]
This function needs more tests (only ut is avaible now). So I don't think this function is stable.
And the function is not compatible with openCypher, so it should be disscussed and approved by PM.
