### ISSUE TITLE
Highlight `OR` not supported in LOOKUP WHERE for doc version 1.2.0

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#393]
https://discuss.nebula-graph.com.cn/t/topic/3876/3

https://docs.nebula-graph.com.cn/1.2.0/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/where-syntax/

Maybe apart from the highlight, also to point out the mitigation(like to use `UNION` instead as @bright-starry-sky suggested?)

Thanks!

**Comment by cooper-lzy** [comment]
fixed the problem in [LOOKUP 语法](https://github.com/vesoft-inc/nebula-docs-cn/blob/v1.2.1/docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md)

**Comment by wey-gu** [comment]
> fixed the problem in [LOOKUP 语法](https://github.com/vesoft-inc/nebula-docs-cn/blob/v1.2.1/docs/manual-CN/2.query-language/4.statement-syntax/2.data-query-and-manipulation-statements/lookup-syntax.md).

Does it seem we cannot use `UNION` here to replace `OR`? instead, we have to mitigate to use it like to enable two conditions' `OR`?
```
LOOKUP ON {<vertex_tag> | <edge_type>} WHERE <expressionA>
  UNION
 LOOKUP ON {<vertex_tag> | <edge_type>} WHERE <expressionB>
```
