### ISSUE TITLE
WHERE及YIELD文档中都应该关联引用符的说明

### ISSUE THREAD

**Issue by xiaoronghuang** [vesoft-inc/nebula-docs-cn#422]
[WHERE](https://github.com/vesoft-inc/nebula-docs-cn/blob/5721fc0d6987e7b50781997d56046bb8201eca8f/docs-2.0/3.ngql-guide/8.clauses-and-options/where.md)和[YIELD](https://github.com/vesoft-inc/nebula-docs-cn/blob/ee8330ec78df37772302c15b5e9243049878dd7d/docs-2.0/3.ngql-guide/8.clauses-and-options/yield.md)子句中都需要使用[引用符](https://github.com/vesoft-inc/nebula-docs-cn/blob/master/docs-2.0/3.ngql-guide/5.operators/5.property-reference.md)关联属性，文档没有说明也没有关联相关说明文档，是否应该添加下关联说明？

**Comment by wey-gu** [comment]
Dear @xiaoronghuang 

Thanks a lot for pointing out this,
it's true that adding references within `WHERE` & `YIELD` themselves will help.

Would you mind provide a PR on this?

**Comment by cooper-lzy** [comment]
#437

**Comment by wey-gu** [comment]
close it, as PR#437 addressed it.
