### ISSUE TITLE
第一章简介#数据结构链接404

### ISSUE THREAD

**Issue by collabH** [vesoft-inc/nebula-docs-cn#460]
![image](https://user-images.githubusercontent.com/40719512/118614607-8702ac00-b7f2-11eb-8ec4-8c261ca66786.png)

这里^Tag点进去404

**Comment by wey-gu** [comment]
Thank you @collabH!

Dear @cooper-lzy,

could you help check this?
https://docs.nebula-graph.com.cn/2.0.1/1.introduction/2.data-model/
Does it seem the hyperlink is not intended?

Thanks!

**Comment by wey-gu** [comment]
update: It's already fixed thanks @cooper-lzy :-).

Thank you @collabH  again!
