### ISSUE TITLE
Add latest alias for versioned URLs

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#462]
We could consider adding an alias to the latest version of docs, this is helpful when we would like to refer some chapters(that's basically not changed among versions) always to its latest version.

This was triggered in discussion in this PR https://github.com/vesoft-inc/nebula/pull/2476. cc @jamieliu1023  @yihong0618

It's feasible via https://squidfunk.github.io/mkdocs-material/setup/setting-up-versioning/#publishing-a-new-version, which I quote as below:

Publishing a new version¶
If you want to publish a new version of your project documentation, choose a version identifier and update the alias set as the default version with:

```
mike deploy --push --update-aliases 0.1 latest
```
Note that every version will be deployed as a subdirectory of your site_url, e.g.:

- docs.example.com/0.1/
- docs.example.com/0.2/
- ...
Setting a default version¶
When starting with mike, a good idea is to set an alias as a default version, e.g. latest, and when publishing a new version, always update the alias to point to the latest version:
```
mike set-default --push latest
```

Thanks.

**Comment by whitewum** [comment]
Unfortunately, the structure of docs might change between versions. And it changes frequently as the product changes all the time. So I prefer not to jump to any sections by default (by now).

I've already set the latest stable version as default. And I might add a tag of `latest` later.
