### ISSUE TITLE
Incorrect markdown on web page

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula-docs-cn#494]
As title.
link: https://docs.nebula-graph.com.cn/2.0.1/nebula-exchange/about-exchange/ex-ug-limitations/
It looks good in the GitHub preview though.
![image](https://user-images.githubusercontent.com/18348405/119290470-21de0900-bc7f-11eb-90d5-454b8bd72eea.png)

**Comment by cooper-lzy** [comment]
The problem has been fixed, thanks.
