### ISSUE TITLE
How about add spaces before and after each word?

### ISSUE THREAD

**Issue by jyz0309** [vesoft-inc/nebula-docs-cn#640]
直接用中文吧:)
我发现 nebula 中文文档在一些地方会有着英语风格不统一的问题。
举个例子：
在[升级历史版本到 v2.0.0](https://docs.nebula-graph.com.cn/2.0.1/4.deployment-and-installation/3.upgrade-nebula-graph/)之中
![image](https://user-images.githubusercontent.com/38248129/123138712-f1f57180-d487-11eb-87a6-359352614ff4.png)
前面的 `Storaged` 的前后都会有空格，而在下文中的 `Storaged` 的前后却没有空格，这样会显得文档整体非常的乱 : )
和这个差不多的有挺多地方 😏
不如一起改一改？: )😏

**Comment by wey-gu** [comment]
@jyz0309 welcome for PRs :-), I think we should go with the approach with spaces.
Please @whitewum @cooper-lzy @randomJoe211  correct me if wrong :-)

**Comment by jyz0309** [comment]
> @jyz0309 welcome for PRs :-), I think we should go with the approach with spaces.
> Please @whitewum @cooper-lzy @randomJoe211 correct me if wrong :-)

Agreed. Because I think spaces will make the doc not so crowded 🤔. 
Just like 
一个Nebula集群里面有Meta服务、Graph服务、还有Storage服务
And 
一个 Nebula 集群里面有 Meta 服务、Graph 服务、还有 Storage 服务
I like the second 🥇

**Comment by whitewum** [comment]
行，下次看看有没有脚本可以处理这个问题。

**Comment by abby-cyber** [comment]
already fixed the whitespace issue. Thank you all!
