### ISSUE TITLE
Scale in storaged href link 404 in FQA cn/en version 2.0.1 and master branch

### ISSUE THREAD

**Issue by Reid00** [vesoft-inc/nebula-docs-cn#694]
Scale in storaged in FQA, Balance remove command linked page 404.

- [cn] https://docs.nebula-graph.com.cn/2.0.1/2.quick-start/0.FAQ/#_9
![image](https://user-images.githubusercontent.com/38450639/124572005-de300f00-de7a-11eb-9ae7-db0128dc7709.png)

- [en]https://docs.nebula-graph.io/master/19.FAQ/0.FAQ/
![image](https://user-images.githubusercontent.com/38450639/124572064-ec7e2b00-de7a-11eb-8d51-771701cdad6c.png)

**Comment by cooper-lzy** [comment]
Thank you for your feedback, we have fixed these problems.
