### ISSUE TITLE
[question] about non-property index and property index

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#708]
Dear,

From [match-tag](https://docs.nebula-graph.com.cn/master/3.ngql-guide/7.general-query-statements/2.match/#tag), it's stated that:
> Tag的索引和属性的索引不同。如果Tag的某个属性有索引，但是Tag本身没有索引，用户无法基于该Tag执行MATCH语句。

While in [create index](https://docs.nebula-graph.com.cn/master/3.ngql-guide/14.native-index-statements/1.create-native-index/), it mentioned that:
> 如果已经为"某个Tag T的属性A"建立过属性索引i_TA，则没有必要对于Tag T额外再建立一个Tag索引i_T。这是因为查询引擎可以使用i_TA来替代i_T。Edge type索引同理。但是，i_T却不能替代i_TA用于属性查找。

How should I understand this, please?
Thanks!
BR, Wey

**Comment by whitewum** [comment]
你可以试试，应该在某个中间版本加上了属性索引替代tag索引。
所以前一句的限制就取消了。

**Comment by wey-gu** [comment]
> 你可以试试，应该在某个中间版本加上了属性索引替代tag索引。
> 所以前一句的限制就取消了。

多谢吴老师，明白了 :-)
