### ISSUE TITLE
2.0.1文档中引用符这一节的示例代码有误。

### ISSUE THREAD

**Issue by JustDoItGit** [vesoft-inc/nebula-docs-cn#724]
[引用符](https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/5.operators/5.property-reference/)
这一段的示例代码错误，
示例中age错写成name了。
```sql
GO FROM "player100" OVER follow YIELD $^.player.age AS SrcAge, $$.player.age AS DestAge;
```

**Comment by wey-gu** [comment]
Dear @JustDoItGit,
Good catch!! Would you mind help fix this with a PR, just click the ✎ icon on that doc page:

<img width="825" alt="Screen Shot 2021-07-15 at 5 27 25 PM" src="https://user-images.githubusercontent.com/1651790/125764777-4048fe96-e448-42aa-8ba8-9ff0c443cb73.png">

**Comment by JustDoItGit** [comment]
ok

**Comment by wey-gu** [comment]
> ok

Thanks a lot, @JustDoItGit, are you going to do it, please? or?
