### ISSUE TITLE
[UPDATE NEEDED] Lookup supports use all relational expression in where clause

### ISSUE THREAD

**Issue by Aiee** [vesoft-inc/nebula-docs-cn#729]
The statement in https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/7.general-query-statements/5.lookup/#where needs to be updated since [this PR](https://github.com/vesoft-inc/nebula-graph/pull/1251) adds support in using all relational expressions as filters in LOOKUP clause, including `starts with, ends with, contains`

**Comment by cooper-lzy** [comment]
modified document in 2.5.0 branch.
https://docs.nebula-graph.com.cn/master/3.ngql-guide/7.general-query-statements/5.lookup/#where
