### ISSUE TITLE
highlights on metrics

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#740]
This is worthy mentioned in metrics documentation:

It turns out that stats like `num_add_vertices.sum.3600` are not actually vertices count, instead, it's the insert count when the batch size of the insert query is not 1, also, in & out also should be aware of in this case.

Thus, the SUM of `num_add_vertices.sum.3600` of all storageD instances is not the actual vertices added of the corresponding period.

----------------
https://discuss.nebula-graph.com.cn/t/topic/4880/10?u=wey

Which I quoted @laura-ding 's clarification as below:

> 现在 metric 统计的 edge 和 vertex 的数量是向storage批量写入的次数，所以当你插入的query含有batch的时候，这个统计就不是实际的点边数量，而是batch数量（当然，边点时候，还有包含每条边的反向边）。假如你每个insert 语句只包含一个点或者一条边，那么，你把集群所有storage统计出来的数据就是点的插入数量，边的话，需要用总数除以2（因为有反向边）

cc @laura-ding

**Comment by whitewum** [comment]
It looks that the behaviour is a bug, and a bit ugly. you can raise the bug in the nebula repo.
