### ISSUE TITLE
will Dump Tool be documented in 2.x?

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#753]
as titled, it's still delivered in binary packages, should corresponding chapters in 1.x be uplifted?

**Comment by whitewum** [comment]
it depends on whether PM releases this tool.

**Comment by whitewum** [comment]
updates: the pm deos not release this tool

@Sophie-Xie

**Comment by Sophie-Xie** [comment]
I discussed it with forest, we will not release the dump tool.
