### ISSUE TITLE
Add more note/highlight for scaling in storageD?

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#790]
We may add more notes here: https://docs.nebula-graph.com.cn/2.0.1/8.service-tuning/load-balance/#storage_1 around:
- it will be removed in show hosts by default in 1 day when a stroageD was removed(in addition to it's in OFFLINE state)
- the timer is controlled by metaD config `removed_threshold_sec`

context: 
https://nebulagraph.slack.com/archives/CSK0RSBFT/p1627912491003500

**Comment by wey-gu** [comment]
Can be closed via #1028 
While maybe we could also add removed_threshold_sec into the metad conf chapter rather than only in the note part of host removal?

**Comment by cooper-lzy** [comment]
Only if the parameter exists in the configuration file, our document describes it.
