### ISSUE TITLE
'shmId’ may be used uninitialized

### ISSUE THREAD

**Issue by NewZsh** [vesoft-inc/nebula-docs-cn#805]
Error below when typing $make following the doc
... FTIndexExecutor.cpp line 83 ...  ‘shmId’ may be used uninitialized in this function [-Werror=maybe-uninitialized]

I add the following line at the beginning of `src/executor/maintain/FTIndexExecutor.cpp`
  > _Pragma ("GCC diagnostic ignored \"-Wmaybe-uninitialized\"")

and it works.

**Comment by whitewum** [comment]
you can raise the issue at  nebula repo, not the doc repo.
