### ISSUE TITLE
Highlight somewhere in docs on property filter in bulk pattern's condition

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#824]
It's easy for users to write:
> incorrect
```
match path=(n:player{name: "Tim Duncan"})-[e:follow*1..2]-(m) \
    where e.degree > 0 \
    return path
```
rather than:
> correct
```
match path=(n:player{name: "Tim Duncan"})-[e:follow*1..2]-(m) \
    where ALL(e_ in e WHERE e_.degree > 0) \
    return path
```

Could we put the correct expression somewhere(and in a highlighted way) in docs?

**Comment by whitewum** [comment]
it's about syntax, not semantics. the examples are tested and works for nebula 2.0.
but if you consider the example necessary, you can add one more example pr to the doc.

**Comment by wey-gu** [comment]
I will do this later, or maybe we could introduce a chapter like a query cheatsheet/ cookbook to include some typical/worth-highlighted query examples?

**Comment by abby-cyber** [comment]
https://docs.nebula-graph.com.cn/2.6.0/2.quick-start/6.cheatsheet-for-ngql-command/ 

cheatsheet for nGQL

**Comment by wey-gu** [comment]
People still fall into this trap today

https://discuss.nebula-graph.com.cn/t/topic/6625/2

**Comment by wey-gu** [comment]
#1266 is trying to help on this trap

- [ ] lift to en docs

**Comment by wey-gu** [comment]
> https://docs.nebula-graph.com.cn/2.6.0/2.quick-start/6.cheatsheet-for-ngql-command/
> 
> cheatsheet for nGQL

Thank you @abby-cyber , I didnt see this cause highlighted in cheatsheet, could we also have this trap highlighted in one of match examples in the cheatsheet?

**Comment by abby-cyber** [comment]
> > https://docs.nebula-graph.com.cn/2.6.0/2.quick-start/6.cheatsheet-for-ngql-command/
> > cheatsheet for nGQL
> 
> Thank you @abby-cyber , I didnt see this cause highlighted in cheatsheet, could we also have this trap highlighted in one of match examples in the cheatsheet?

already added desc for that trap. thank your for your reminding！
