### ISSUE TITLE
Suggest to update the match grammar

### ISSUE THREAD

**Issue by study-day** [vesoft-inc/nebula-docs-cn#845]
https://docs.nebula-graph.com.cn/master/3.ngql-guide/7.general-query-statements/2.match/
```
MATCH <pattern> [<WHERE clause>] RETURN <output>
```
https://docs.nebula-graph.com.cn/2.0.1/3.ngql-guide/8.clauses-and-options/with/
example2
```
 MATCH p=(v:player{name:"Tim Duncan"})--() \
        WITH nodes(p) AS n \
        UNWIND n AS n1 \
        RETURN DISTINCT n1;
```

In Example2 'with', 'unwind' is not a  part of pattern, so should the syntax of match be added?

**Comment by whitewum** [comment]
WITH is not a part of MATCH

**Comment by study-day** [comment]
https://docs.nebula-graph.com.cn/master/3.ngql-guide/1.nGQL-overview/3.graph-patterns/
根据文档  WITH  和UNWIND  不是 patterns 的一部分，如果是的话请在3.graph-patterns中补充。所以在应该在match的语法中表示出来，说明应该怎么用，不然后面大家都不知道为什么下面这段官方查询示例时合法的
``` MATCH p=(v:player{name:"Tim Duncan"})--() \
        WITH nodes(p) AS n \
        UNWIND n AS n1 \
        RETURN DISTINCT n1;
```

**Comment by study-day** [comment]
This is just a suggestion, it’s up to you to decide what to do

**Comment by whitewum** [comment]
WITH 和UNWIND 不是graph patterns的一部分，它们是语法结构的一部分。
