### ISSUE TITLE
It is recommended to add the number of hosts when discussing the problem

### ISSUE THREAD

**Issue by study-day** [vesoft-inc/nebula-docs-cn#858]
https://docs.nebula-graph.com.cn/master/20.appendix/0.FAQ/
可以在CREATE SPACE时设置replica_factor为偶数（例如设置为2）吗？

在这个问题讨论中主机数量是多少？请补充在文档中

**Comment by cooper-lzy** [comment]
感谢建议，已经进行了补充。
