### ISSUE TITLE
the image is not found

### ISSUE THREAD

**Issue by study-day** [vesoft-inc/nebula-docs-cn#861]
https://docs.nebula-graph.com.cn/master/8.service-tuning/2.graph-modeling/#_9 the image is not found
https://cdn.cms-twdigitalassets.com/content/dam/blog-twitter/engineering/en_us/insights/2021/tgn/temporal_graph1.png.img.fullhd.medium.png

**Comment by cooper-lzy** [comment]
Thanks for feedback, fixed.
