### ISSUE TITLE
pdf转换异常

### ISSUE THREAD

**Issue by dbacyj** [vesoft-inc/nebula-docs-cn#863]
![image](https://user-images.githubusercontent.com/72034305/129868236-5c036646-b2e9-4797-b7c3-85c4b5ac8e18.png)
![image](https://user-images.githubusercontent.com/72034305/129868293-8cf65c24-881c-467b-87c5-7fb6bc8009a2.png)

转换成pdf后被截断了

**Comment by cooper-lzy** [comment]
是这个链接 ：https://docs.nebula-graph.com.cn/site/pdf/NebulaGraph-book.pdf
还是文档官网的pdf：https://docs.nebula-graph.com.cn/master/
我这边查看了所有途径的pdf都是正常的。
![image](https://user-images.githubusercontent.com/78672629/129994723-f0b32c99-36f5-4b07-a15e-9e5d4e2e5421.png)
![image](https://user-images.githubusercontent.com/78672629/129994763-f4218092-5a77-4723-a79f-ca97721b0a97.png)

**Comment by whitewum** [comment]
![image](https://user-images.githubusercontent.com/50101159/130191714-855eb179-e7e2-4352-9c25-a000b534140b.png)

works fine on
 
windows 10 & chrome.
