### ISSUE TITLE
Description naming rules

### ISSUE THREAD

**Issue by hebelala** [vesoft-inc/nebula-docs-cn#871]
Description naming rules for nGQL, such as space_name, tag_name, vertex_name, edge_name, prop_name. It just can include character, number, underline !?

**Comment by cooper-lzy** [comment]
Yes, the chinese document has a detailed description, but the english document has not been updated in time.

https://docs.nebula-graph.com.cn/master/3.ngql-guide/10.tag-statements/1.create-tag/

**Comment by hebelala** [comment]
ok, thanks~
