### ISSUE TITLE
[1.2.1] typo, extra comma in nGQL commands

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#899]
https://docs.nebula-graph.com.cn/1.2.1/manual-CN/1.overview/2.quick-start/4.import-csv-file/

> now

```ngql
nebula> CREATE EDGE follow (degree, int);
```

> expected

```ngql
nebula> CREATE EDGE follow (degree int);
```

**Comment by whitewum** [comment]
great! 
can you help to fix this?
Click the pencil button.

**Comment by wey-gu** [comment]
> great!
> can you help to fix this?
> Click the pencil button.

Oops, I accidentally directly committed it instead of creating a PR, should I revert and make it into a PR or?

**Comment by whitewum** [comment]
it 's ok.
