### ISSUE TITLE
BR tool doesn't appear in the menu on the left side

### ISSUE THREAD

**Issue by xiajingchun** [vesoft-inc/nebula-docs-cn#921]
for v2.5
![image](https://user-images.githubusercontent.com/6269380/131279941-fb269631-7db2-4b67-a741-fc71f19c7304.png)
It does exist in the English doc.

**Comment by whitewum** [comment]
br is not released in v2.5.

**Comment by xiajingchun** [comment]
I see. You might want to take a look at the English doc, BR is listed there even in v2.0.1.
