### ISSUE TITLE
font size in the nebula book

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#932]
The font size is smaller than averages ones, it's actually quite read-friendly on the big screen in zoomed scale, while, in some other cases, i.e. some reading devices, it's too small.

Could we enlarge the font size?(Aha, I know it will end up with many more pages)

Thanks!

context:
- One of our contributor mentioned this to me today :-)

**Comment by whitewum** [comment]
You are welcome to generate a specific version for him.  All texts and tools are based on open source.  tips: try `mkdoc.yml`.

But the default font is designed for 4k screen for the majority of uses.

**Comment by wey-gu** [comment]
cc @hezhizhen
