### ISSUE TITLE
note's link:使用RPM/DEB包部署集群 is confusing in RPM/DEB installation page

### ISSUE THREAD

**Issue by wey-gu** [vesoft-inc/nebula-docs-cn#992]
https://docs.nebula-graph.com.cn/2.5.1/2.quick-start/2.install-nebula-graph/

the link of `使用RPM/DEB包部署集群` will be linked to requirements rather than its actual meaning?

<img width="455" alt="Screen Shot 2021-09-22 at 5 02 13 PM" src="https://user-images.githubusercontent.com/1651790/134314833-e55f5921-e91e-4ced-800b-59bb952bec47.png">

**Comment by foesa-yang** [comment]
Thank you for your comments, I have modified the document.
