### ISSUE TITLE
Move some job related command from WriteSpace to Job

### ISSUE THREAD

**Issue by SuperYoko** [vesoft-inc/nebula-docs-cn#999]
To fix this issue:
https://github.com/vesoft-inc/nebula/issues/2611

I give this pr:
https://github.com/vesoft-inc/nebula-docs-cn/pull/969

And now I see that some commands are in both Job and WriteSpace row, I need somebody to confirm this.

  |权限|God  |Admin|DBA|User|Guest|相关语句|
  |:---|:---|:---|:---|:---|:---|:---|
  |Write space|Y|||||`CREATE SPACE`、`DROP SPACE`、`CREATE SNAPSHOT`、`DROP SNAPSHOT`、`BALANCE DATA`、`BALANCE DATA STOP`、`BALANCE DATA REMOVE`、`BALANCE LEADER`、`ADMIN`、`CONFIG`、`INGEST`、`DOWNLOAD`、`SUBMIT JOB COMPACT`、`SUBMIT JOB FLUSH`、`SUBMIT JOB STATS`、`STOP JOB`、`RECOVER JOB`、`BUILD TAG INDEX`、`BUILD EDGE INDEX`|
  |Job|Y|Y|Y|Y||`SUBMIT JOB COMPACT`、`SUBMIT JOB FLUSH`、`SUBMIT JOB STATS`、`STOP JOB`、`RECOVER JOB`|

**Comment by cooper-lzy** [comment]
The document has been modified.
